import type { TourPackage, GalleryImage, VisaCountry } from "./admin-types";

export const initialPackages: TourPackage[] = [
  {
    id: "1",
    title: "Maldives Beach Paradise",
    slug: "maldives-beach-paradise",
    price: "PKR 249,000",
    location: "Maldives",
    category: "Popular Packages",
    duration: "5 Days / 4 Nights",
    groupSize: "02-08",
    image: "/images/client/tours/Maldives.png",
    description: "Escape to the turquoise waters and powdery white sands of the Maldives.",
  },
  {
    id: "2",
    title: "Bali Adventure Escape",
    slug: "bali-adventure-escape",
    price: "PKR 189,000",
    location: "Indonesia",
    category: "Popular Packages",
    duration: "6 Days / 5 Nights",
    groupSize: "02-10",
    image: "/images/client/tours/Bali--Indoneshia.png",
    description: "Discover the magic of Bali with temples, rice terraces and beaches.",
  },
  {
    id: "3",
    title: "Turkey Cultural Tour",
    slug: "turkey-cultural-tour",
    price: "PKR 219,000",
    location: "Turkey",
    category: "Group Tour",
    duration: "7 Days / 6 Nights",
    groupSize: "10-25",
    image: "/images/client/tours/Turkey.png",
    description: "Explore Istanbul, Cappadocia and Ephesus on this cultural journey.",
  },
  {
    id: "4",
    title: "Thailand Honeymoon",
    slug: "thailand-honeymoon",
    price: "PKR 159,000",
    location: "Thailand",
    category: "Honeymoon",
    duration: "5 Days / 4 Nights",
    groupSize: "02",
    image: "/images/client/tours/Thailand.png",
    description: "Romantic getaway to Phuket and Krabi with luxury resorts.",
  },
  {
    id: "5",
    title: "Japan Discovery",
    slug: "japan-discovery",
    price: "PKR 349,000",
    location: "Japan",
    category: "Customized",
    duration: "10 Days / 9 Nights",
    groupSize: "02-06",
    image: "/images/client/tours/Japan-Customized-Tour.png",
    description: "Experience Tokyo, Kyoto and Osaka with guided cultural tours.",
  },
  {
    id: "6",
    title: "Dubai City Break",
    slug: "dubai-city-break",
    price: "PKR 129,000",
    location: "UAE",
    category: "One Day Trip",
    duration: "4 Days / 3 Nights",
    groupSize: "02-15",
    image: "/images/client/tours/Dubai.png",
    description: "Explore Dubai's iconic landmarks, desert safari and shopping.",
  },
  {
    id: "7",
    title: "Egypt Pyramids Tour",
    slug: "egypt-pyramids-tour",
    price: "PKR 279,000",
    location: "Egypt",
    category: "Educational",
    duration: "8 Days / 7 Nights",
    groupSize: "05-20",
    image: "/images/client/tours/Egypt-Customized-Tour.jpg",
    description: "Visit the Great Pyramids, Nile cruise and ancient temples.",
  },
  {
    id: "8",
    title: "Europe Grand Tour",
    slug: "europe-grand-tour",
    price: "PKR 499,000",
    location: "Europe",
    category: "Group Tour",
    duration: "14 Days / 13 Nights",
    groupSize: "10-30",
    image: "/images/client/tours/Europe.png",
    description: "France, Italy, Switzerland and Germany in one epic journey.",
  },
  {
    id: "9",
    title: "Skardu Valley Adventure",
    slug: "skardu-valley-adventure",
    price: "PKR 89,000",
    location: "Pakistan",
    category: "Last Minute Deal",
    duration: "5 Days / 4 Nights",
    groupSize: "04-12",
    image: "/images/client/tours/Skardu--Pakistan--2-.png",
    description: "Discover the breathtaking landscapes of Skardu and Gilgit.",
  },
  {
    id: "10",
    title: "Saudi Arabia Umrah",
    slug: "saudi-arabia-umrah",
    price: "PKR 199,000",
    location: "Saudi Arabia",
    category: "Group Tour",
    duration: "10 Days / 9 Nights",
    groupSize: "20-50",
    image: "/images/client/tours/Saudi-Arabia-Customized-Tour.png",
    description: "Complete Umrah package with flights, hotel and guided ziyarat.",
  },
];

export const initialGallery: GalleryImage[] = [
  { id: "g1", src: "/images/client/HallStatt.jpg.jpeg", title: "Hallstatt Village", location: "Hallstatt, Austria" },
  { id: "g2", src: "/images/client/tours/Australia.webp", title: "Sydney Opera House", location: "Sydney, Australia" },
  { id: "g3", src: "/images/client/tours/Baku--Azerbaijan.png", title: "Baku City View", location: "Baku, Azerbaijan" },
  { id: "g4", src: "/images/client/tours/China-Customized-Tour.png", title: "Great Wall of China", location: "Beijing, China" },
  { id: "g5", src: "/images/client/tours/Dubai.png", title: "Dubai Skyline", location: "Dubai, UAE" },
  { id: "g6", src: "/images/client/tours/Egypt-Customized-Tour.jpg", title: "Pyramids of Giza", location: "Cairo, Egypt" },
  { id: "g7", src: "/images/client/tours/England.avif", title: "London Bridge", location: "London, England" },
  { id: "g8", src: "/images/client/tours/Europe.png", title: "European Countryside", location: "Europe" },
  { id: "g9", src: "/images/client/tours/Italy.avif", title: "Rome Colosseum", location: "Rome, Italy" },
  { id: "g10", src: "/images/client/tours/Japan-Customized-Tour.png", title: "Mount Fuji", location: "Tokyo, Japan" },
  { id: "g11", src: "/images/client/tours/Maldives.png", title: "Maldives Beach", location: "Maldives" },
  { id: "g12", src: "/images/client/tours/Thailand.png", title: "Bangkok Temple", location: "Bangkok, Thailand" },
  { id: "g13", src: "/images/client/tours/Turkey.png", title: "Istanbul Hagia Sophia", location: "Istanbul, Turkey" },
  { id: "g14", src: "/images/client/tours/Norway.jpg", title: "Norway Fjords", location: "Norway" },
  { id: "g15", src: "/images/client/tours/Singapore-Customized-Tour.png", title: "Marina Bay Sands", location: "Singapore" },
];

export const initialVisa: VisaCountry[] = [
  { country: "Azerbaijan", requirements: ["Scanned copy of passport bio page."] },
  { country: "Bahrain", requirements: ["Scanned copy of CNIC (Front & Back)", "Scanned copy of Passport Bio Page", "Passport size white background picture", "Family Registration Certificate (FRC)", "3-6 Months Bank Statement (Minimum Balance)"] },
  { country: "Canada", requirements: ["Passport (All Used Pages)", "Family Registration Certificate (FRC)", "Marriage Registration Certificate (MRC) (if applicable)", "Business Registration Certificate (for business owners)", "Bank Statement (Last 6 Months) & Account Maintenance Certificate", "Recent Passport-Size Photograph", "Employment Letter", "Last 3 Months' Salary Slip"] },
  { country: "China", requirements: ["Passport copy of 1st & 2nd page (Must be valid for 6 months)", "Copy of CNIC (Front & Back)", "Return/Onward ticket reservation", "3 recent passport size photographs with white background", "Personal/Company bank statement of the last 6 months with bank letter", "Hotel reservation"] },
  { country: "Egypt", requirements: ["Passport valid until at least 8 months+ with photocopies", "3 photographs in white background 2×2 size", "Last 6 months Personal Bank statement", "Request letter on company letterhead", "Polio Vaccination card", "A Copy of Original ID Card and FRC"] },
  { country: "Europe", requirements: ["Passport (All Used Pages)", "Family Registration Certificate (FRC)", "Bank Statement (Last 6 Months) & Account Maintenance Certificate", "Recent Passport-Size Photograph", "Travel Insurance (Minimum coverage: €30,000)", "Job letter/Leave letter (For employees)"] },
  { country: "Indonesia", requirements: ["Scanned copy of Passport 1st & 2nd page (Must be valid for 6 months)", "Scanned copy of CNIC (Front & back)", "Last 6 months bank statement (Minimum balance 5 Lac)", "Bank maintenance letter"] },
  { country: "Japan", requirements: ["Visa Application Form", "Passport valid for at least 8 months + photocopies", "3 passport-size photographs with white background", "Last 6 months Parents'/Sponsor's Bank Statement", "Confirmed Hotel Reservation", "Employment Proof of Parents"] },
  { country: "Malaysia", requirements: ["Scanned copy of CNIC", "Scanned copy of passport 1st & 2nd page", "Passport size white background picture"] },
  { country: "Maldives", requirements: ["Confirmed return/onward flight ticket", "Pre-paid hotel reservation", "Sufficient funds (Cash or card, approx. 50$ to 100$ per day)"] },
  { country: "Philippines", requirements: ["06 months valid passport + previous passports", "04 white background passport size photos", "Colorful copy of ID Card/CNIC", "06 months bank statement with Bank maintenance letter", "Must have closing balance of 400,000 in account"] },
  { country: "Schengen", requirements: ["Valid Passport (valid at least 3 months after return date)", "Completed Schengen visa application form", "Travel Insurance (Minimum coverage: €30,000)", "Flight reservation/itinerary", "Hotel booking or invitation letter", "Last 6 months bank statement", "Salary slips / Business Proof"] },
  { country: "Singapore", requirements: ["Scanned copy of CNIC", "Scanned Copy of Passport 1st & 2nd Page", "Passport size white background picture", "Family Registration Certificate (FRC)"] },
  { country: "Sri Lanka", requirements: ["Scanned copy of CNIC", "Scanned copy of 1st & 2nd page of passport", "Passport size white background picture"] },
  { country: "Thailand", requirements: ["Old & current passports", "2 Copies of CNIC", "6 Months bank statement", "2 Passport size pictures with white background", "Bank account maintenance letter"] },
  { country: "Turkey", requirements: ["Original Passport with 6 month validity", "02 white background pictures (5cm x 5cm)", "Scanned copy of CNIC (Front & back)", "Last 06 Months Bank Statement", "Valid polio vaccination certificate"] },
  { country: "Tajikistan", requirements: ["Original passport with at least 6 months validity", "Scanned copy of the passport's bio-data page", "Recent passport-size photograph (digital, white background)", "Confirmed or tentative flight itinerary"] },
  { country: "Umrah", requirements: ["Scanned copy of passport bio page", "Scanned copy of CNIC/ID Card (Front & back)", "Picture with white background", "Polio vaccination certificate", "Confirmed Return Air Tickets"] },
  { country: "Uzbekistan", requirements: ["Original passport", "Picture with white background", "ID Card/CNIC", "Bank statement (Minimum closing balance 4 Lac–5 Lac)", "Confirm hotel booking"] },
  { country: "United Kingdom", requirements: ["Passport (All Used Pages)", "Family Registration Certificate (FRC)", "Bank Statement (Last 6 Months)", "Recent Passport-Size Photograph", "Employment Letter", "Last 3 Months' Salary Slip"] },
  { country: "United States", requirements: ["Passport & CNIC", "2 Passport Size Pictures", "Permanent Home Address", "Social Media Profile Links", "Business Name, Address & Contact Number", "Highest Qualification / Last Degree"] },
];
