export const IMG = "https://demo.egenslab.com/html/gofly/preview/assets/img";

import { clientHeroSlides, clientGalleryImages, clientGalleryItems } from "@/lib/client-images";

export const heroSlides = clientHeroSlides;

export type PkgCategory = "group" | "honeymoon" | "corporate" | "customized" | "educational";

export type Pkg = {
  images: string[];
  badge?: string;
  title: string;
  location: string;
  duration?: string;
  price: string;
  oldPrice?: string;
  slug: string;
  rating?: number;
  reviews?: number;
  category?: PkgCategory;
};

export const popularPackages: Pkg[] = [
  {
    images: ["/images/client/tours/Maldives.png"],
    badge: "Hot Sale!",
    title: "Maldives Beach Paradise",
    location: "Maldives",
    duration: "05 Days",
    price: "$399",
    slug: "maldives-beach-paradise",
    rating: 4.5,
    reviews: 134,
  },
  {
    images: ["/images/client/tours/Bali--Indoneshia.png"],
    badge: "Hot Sale!",
    title: "Bali Paradise Tour",
    location: "Indonesia",
    duration: "07 Days",
    price: "$599",
    slug: "bali-paradise-tour",
    rating: 4.6,
    reviews: 98,
  },
  {
    images: ["/images/client/tours/Thailand.png"],
    title: "Phuket & Krabi Island",
    location: "Thailand",
    duration: "10 Days",
    price: "$499",
    slug: "phuket-krabi-island",
    rating: 4.4,
    reviews: 76,
  },
  {
    images: ["/images/client/tours/Italy.avif"],
    title: "Rome, Florence & Venice",
    location: "Italy, France",
    duration: "08 Days/07 Nights",
    price: "$999",
    slug: "rome-florence-venice",
    rating: 4.8,
    reviews: 156,
  },
  {
    images: ["/images/client/tours/Egypt-Customized-Tour.jpg"],
    title: "Egypt & Nile Cruise Adventure",
    location: "Egypt",
    duration: "10 Days",
    price: "$499",
    slug: "egypt-nile-cruise-adventure",
    rating: 4.3,
    reviews: 64,
  },
  {
    images: ["/images/client/tours/Norway.jpg"],
    badge: "Hot Sale!",
    title: "Norway Northern Lights",
    location: "Norway",
    duration: "07 Days/06 Nights",
    price: "$359",
    slug: "norway-northern-lights",
    rating: 4.9,
    reviews: 210,
  },
];

export const oneDayTrips: Pkg[] = [
  {
    images: ["/images/client/tours/Vietnam-Customized-Tour.png"],
    badge: "Hot Sale!",
    title: "Hanoi Kiem Lake",
    location: "Hanoi, Vietnam",
    price: "$99",
    slug: "hanoi-kiem-lake",
  },
  {
    images: [`${IMG}/home1/tour-package-img11.jpg`],
    title: "Newlands Safari Forest",
    location: "South Africa",
    price: "$89",
    slug: "newlands-safari-forest",
  },
  {
    images: ["/images/client/tours/Vietnam-Customized-Tour.png"],
    badge: "Hot Sale!",
    title: "Ho Chi Minh City (Saigon)",
    location: "Saigon, Vietnam",
    price: "$69",
    slug: "ho-chi-minh-city",
  },
  {
    images: ["/images/client/tours/Vietnam-Customized-Tour.png"],
    title: "Halong Bay Cruise",
    location: "Quang Ninh, Vietnam",
    price: "$120",
    slug: "halong-bay-cruise",
  },
];

export const lastMinuteDeals: Pkg[] = [
  {
    images: ["/images/client/tours/Japan-Customized-Tour.png"],
    badge: "Hot Sale!",
    title: "Japan Cherry Blossom",
    location: "Tokyeo, Japan",
    duration: "06 Days",
    price: "$399",
    oldPrice: "$999",
    slug: "japan-cherry-blossom",
    rating: 4.7,
    reviews: 143,
  },
  {
    images: ["/images/client/tours/Dubai.png"],
    badge: "20% off",
    title: "Abu Dhabi Luxury Escape",
    location: "UAE, Qatar",
    duration: "05 Days/04 Nights",
    price: "$720",
    oldPrice: "$899",
    slug: "abu-dhabi-luxury-escape",
    rating: 4.5,
    reviews: 89,
  },
  {
    images: [`${IMG}/home1/tour-package-img9.jpg`],
    badge: "15% off",
    title: "Morocco Desert & City Adventure",
    location: "Europe",
    duration: "07 Days/06 Nights",
    price: "$339",
    oldPrice: "$399",
    slug: "morocco-desert-city-adventure",
    rating: 4.4,
    reviews: 57,
  },
  {
    images: [`${IMG}/home1/tour-package-img17.jpg`],
    badge: "10% off",
    title: "Santorini Island Hopping",
    location: "Greece",
    duration: "04 Days/03 Nights",
    price: "$450",
    oldPrice: "$500",
    slug: "santorini-island-hopping",
    rating: 4.8,
    reviews: 122,
  },
];

export const destinations = [
  { img: "/images/client/tours/China-Customized-Tour.png", title: "Great Wall of China", tours: "Tours (12)" },
  { img: `${IMG}/home2/destination-img2.jpg`, title: "Rome, Italy", tours: "Tours (06)" },
  { img: `${IMG}/home2/destination-img3.jpg`, title: "Machu Picchu of Peru", tours: "Tours (16)" },
  { img: `${IMG}/home2/destination-img4.jpg`, title: "Great Temple Jordan", tours: "Tours (10)" },
  { img: `${IMG}/home2/destination-img5.jpg`, title: "Athens Greece", tours: "Tours (12)" },
  { img: `${IMG}/home2/destination-img6.jpg`, title: "Switzerland", tours: "Tours (26)" },
  { img: `${IMG}/home2/destination-img7.jpg`, title: "Norway", tours: "Tours (08)" },
];

export const blogPosts = [
  {
    img: `${IMG}/home2/blog-img1.jpg`,
    date: "02 Jan.",
    location: "Tokyeo, Japan",
    title: "Nature, Culture & Thrill: Travel Stories That Inspire.",
  },
  {
    img: `${IMG}/home2/blog-img2.jpg`,
    date: "04 Feb.",
    location: "Dubai, Middle East",
    title: "Top 10 Beaches to Visit This Summer Season.",
  },
  {
    img: `${IMG}/home2/blog-img3.jpg`,
    date: "07 Feb.",
    location: "Tokyeo, Japan",
    title: "Dream. Explore. Discover. Where Will You Go Next?",
  },
];

export const testimonials = [
  {
    title: "Excellent Tourist Place!",
    text: "Our honeymoon package to the Maldives was beyond amazing! The travel agency took care of every detail.",
    img: `${IMG}/home1/testimonial-author-img1.png`,
    name: "Robert Kcarery",
    role: "GoFly Traveler",
  },
  {
    title: "Average Experience",
    text: "The Thailand tour was flawless! Great hotels, smooth transfers — truly a stress-free and enjoyable experience.",
    img: `${IMG}/home1/testimonial-author-img3.png`,
    name: "James Bonde",
    role: "GoFly Traveler",
  },
  {
    title: "Great Experience!",
    text: "Thanks to their expert planning, our Dubai vacation was seamless. Every detail was handled with care.",
    img: `${IMG}/home1/testimonial-author-img2.png`,
    name: "Selina Henry",
    role: "GoFly Traveler",
  },
  {
    title: "Great Visitors Venue!",
    text: "We had an incredible Europe tour! The itinerary, bookings, and support were all professionally managed.",
    img: `${IMG}/home1/testimonial-author-img4.png`,
    name: "Michael D Linda",
    role: "GoFly Traveler",
  },
  {
    title: "Fantastic Service!",
    text: "Our trip to Bali was unforgettable! Everything was perfectly organized by the agency from start to finish.",
    img: `${IMG}/home1/testimonial-author-img5.png`,
    name: "Amber Lashley",
    role: "GoFly Traveler",
  },
];

export const counters = [
  { value: 26, suffix: "K+", label: "Tour Completed" },
  { value: 12, suffix: "+", label: "Travel Experience" },
  { value: 20, suffix: "+", label: "Happy Traveler" },
  { value: 98, suffix: "%", label: "Retention Rate" },
];

export const galleryImages = clientGalleryImages;

export const galleryItems = clientGalleryItems.map((item) => ({
  ...item,
  desc: "A stunning destination curated by Travel Nest for unforgettable journeys.",
}));

export const partners = [1, 2, 3, 4, 5, 6].map((n) => `${IMG}/home1/partner-0${n}.png`);

export const searchDestinations = [
  {
    name: "Cox's Bazar",
    country: "Bangladesh",
    tours: 50,
    flag: `${IMG}/home1/filter-bd-flag.png`,
  },
  {
    name: "Bali Paradaise",
    country: "Indonesia",
    tours: 50,
    flag: `${IMG}/home1/filter-indo-flag.png`,
  },
  { name: "POKHARA", country: "Nepal", tours: 30, flag: `${IMG}/home1/filter-nepal-flag.png` },
  { name: "Himachal", country: "India", tours: 30, flag: `${IMG}/home1/filter-india-flag.png` },
  { name: "Sao Paulo", country: "Brazil", tours: 20, flag: `${IMG}/home1/filter-brazil-flag.png` },
  {
    name: "Bangkok",
    country: "Thailand",
    tours: 40,
    flag: `${IMG}/home1/filter-thailand-flag.png`,
  },
  { name: "Barcelona", country: "Spain", tours: 20, flag: `${IMG}/home1/filter-spain-flag.png` },
  { name: "Burj Khalifa", country: "Dubai", tours: 35, flag: `${IMG}/home1/filter-uae-flag.png` },
  {
    name: "New York",
    country: "United States",
    tours: 45,
    flag: `${IMG}/home1/filter-usa-flag.png`,
  },
];

export const tourCategories = [
  "Family Tour",
  "Honeymoon Tour",
  "Group Tour",
  "Adventure Tour",
  "Solo Tour",
];

export const destinationPageHero = `${IMG}/home2/banner-img2.jpg`;

export const destinationCards = [
  { img: `${IMG}/home2/destination-img2.jpg`, title: "Rome, Italy", tours: "Tours (06)" },
  { img: "/images/client/tours/China-Customized-Tour.png", title: "Great Wall of China", tours: "Tours (12)" },
  { img: `${IMG}/home2/destination-img4.jpg`, title: "Great Temple Jordan", tours: "Tours (18)" },
  { img: `${IMG}/home2/destination-img6.jpg`, title: "Switzerland", tours: "Tours (14)" },
  { img: `${IMG}/home2/destination-img5.jpg`, title: "Santorini, Greece", tours: "Tours (07)" },
  { img: `${IMG}/home2/destination-img3.jpg`, title: "Machu Picchu of Peru", tours: "Tours (26)" },
];

export const destinationPackages: Pkg[] = [
  {
    images: [`${IMG}/home2/tour-package-img2.jpg`],
    title: "Santorini Tour",
    location: "Latin Quarter",
    duration: "08 Days",
    price: "$499",
    slug: "santorini-tour",
  },
  {
    images: [`${IMG}/home1/tour-package-img11.jpg`],
    badge: "Hot Sale!",
    title: "Backwaters & Beaches",
    location: "Le Marais",
    duration: "07 Days/06 Nights",
    price: "$359",
    slug: "backwaters-beaches",
  },
  {
    images: ["/images/client/tours/Maldives.png"],
    badge: "Hot Sale!",
    title: "Maldives Beach Paradise",
    location: "Maldives",
    duration: "05 Days",
    price: "$399",
    slug: "maldives-beach-paradise",
    rating: 4.5,
    reviews: 134,
  },
  {
    images: ["/images/client/tours/Italy.avif"],
    title: "Rome, Florence & Venice",
    location: "Italy, France",
    duration: "08 Days/07 Nights",
    price: "$999",
    slug: "rome-florence-venice",
    rating: 4.8,
    reviews: 156,
  },
  {
    images: ["/images/client/tours/Egypt-Customized-Tour.jpg"],
    title: "Egypt & Nile Cruise Adventure",
    location: "Egypt",
    duration: "10 Days",
    price: "$499",
    slug: "egypt-nile-cruise-adventure",
    rating: 4.3,
    reviews: 64,
  },
];

export const groupTourPackages: Pkg[] = [
  {
    images: ["/images/client/tours/Baku--Azerbaijan.png"],
    badge: "Group Tour",
    title: "Baku, Azerbaijan",
    location: "Azerbaijan",
    duration: "05 Days / 04 Nights",
    price: "PKR 235,000",
    slug: "baku-azerbaijan-group-tour",
    category: "group",
    rating: 4.6,
    reviews: 87,
  },
  {
    images: ["/images/client/tours/Dubai.png"],
    badge: "Group Tour",
    title: "Dubai",
    location: "United Arab Emirates",
    duration: "05 Days / 04 Nights",
    price: "PKR 255,000",
    slug: "dubai-group-tour",
    category: "group",
    rating: 4.7,
    reviews: 121,
  },
  {
    images: ["/images/client/tours/Bali--Indoneshia.png"],
    badge: "Group Tour",
    title: "Bali, Indonesia",
    location: "Indonesia",
    duration: "06 Days / 05 Nights",
    price: "PKR 395,000",
    slug: "bali-indonesia-group-tour",
    category: "group",
    rating: 4.8,
    reviews: 96,
  },
  {
    images: ["/images/client/tours/Malaysia--Kuala-Lumpur-.png"],
    badge: "Group Tour",
    title: "Malaysia (Kuala Lumpur)",
    location: "Malaysia",
    duration: "06 Days / 05 Nights",
    price: "PKR 295,000",
    slug: "kuala-lumpur-malaysia-group-tour",
    category: "group",
    rating: 4.5,
    reviews: 74,
  },
  {
    images: ["/images/client/tours/Thailand.png"],
    badge: "Group Tour",
    title: "Thailand (Bangkok, Phuket & Krabi)",
    location: "Thailand",
    duration: "09 Days / 08 Nights",
    price: "PKR 395,000",
    slug: "thailand-bangkok-phuket-krabi-group-tour",
    category: "group",
    rating: 4.6,
    reviews: 89,
  },
  {
    images: [
      "/images/client/tours/Bali--Indoneshia.png",
      "/images/client/tours/Malaysia--Kuala-Lumpur-.png",
    ],
    badge: "Group Tour",
    title: "Bali & Malaysia",
    location: "Indonesia & Malaysia",
    duration: "08 Days / 07 Nights",
    price: "PKR 449,000",
    slug: "bali-malaysia-group-tour",
    category: "group",
    rating: 4.7,
    reviews: 68,
  },
  {
    images: [
      "/images/client/tours/Thailand.png",
      "/images/client/tours/Malaysia--Kuala-Lumpur-.png",
    ],
    badge: "Group Tour",
    title: "Thailand & Malaysia",
    location: "Thailand & Malaysia",
    duration: "08 Days / 07 Nights",
    price: "PKR 385,000",
    slug: "thailand-malaysia-group-tour",
    category: "group",
    rating: 4.6,
    reviews: 71,
  },
  {
    images: [
      "/images/client/tours/Sri-Lanka.png",
      "/images/client/tours/Thailand.png",
      "/images/client/tours/Malaysia--Kuala-Lumpur-.png",
    ],
    badge: "Group Tour",
    title: "Sri Lanka, Thailand & Malaysia",
    location: "Sri Lanka, Thailand & Malaysia",
    duration: "09 Days / 08 Nights",
    price: "PKR 385,000",
    slug: "sri-lanka-thailand-malaysia-group-tour",
    category: "group",
    rating: 4.5,
    reviews: 63,
  },
  {
    images: ["/images/client/tours/Skardu--Pakistan--2-.png"],
    badge: "Group Tour",
    title: "Skardu, Pakistan",
    location: "Pakistan",
    duration: "04 Days / 03 Nights",
    price: "PKR 115,000",
    slug: "skardu-pakistan-group-tour",
    category: "group",
    rating: 4.9,
    reviews: 132,
  },
];

export const honeymoonPackages: Pkg[] = [
  {
    images: ["/images/client/tours/Bali--Indoneshia.png"],
    badge: "Honeymoon",
    title: "Bali Honeymoon",
    location: "Indonesia",
    duration: "06 Days / 05 Nights",
    price: "PKR 350,000",
    slug: "bali-honeymoon",
    category: "honeymoon",
    rating: 4.8,
    reviews: 102,
  },
  {
    images: ["/images/client/tours/Dubai.png"],
    badge: "Honeymoon",
    title: "Dubai Honeymoon",
    location: "United Arab Emirates",
    duration: "05 Days / 04 Nights",
    price: "PKR 325,000",
    slug: "dubai-honeymoon",
    category: "honeymoon",
    rating: 4.7,
    reviews: 84,
  },
  {
    images: ["/images/client/tours/Maldives.png"],
    badge: "Honeymoon",
    title: "Maldives Honeymoon",
    location: "Maldives",
    duration: "05 Days / 04 Nights",
    price: "PKR 550,000",
    slug: "maldives-honeymoon",
    category: "honeymoon",
    rating: 4.9,
    reviews: 156,
  },
  {
    images: ["/images/client/tours/Thailand.png"],
    badge: "Honeymoon",
    title: "Thailand Honeymoon",
    location: "Thailand",
    duration: "07 Days / 06 Nights",
    price: "PKR 385,000",
    slug: "thailand-honeymoon",
    category: "honeymoon",
    rating: 4.6,
    reviews: 77,
  },
  {
    images: ["/images/client/tours/Turkey.png"],
    badge: "Honeymoon",
    title: "Turkey Honeymoon",
    location: "Turkey",
    duration: "07 Days / 06 Nights",
    price: "PKR 420,000",
    slug: "turkey-honeymoon",
    category: "honeymoon",
    rating: 4.7,
    reviews: 91,
  },
  {
    images: ["/images/client/tours/Baku--Azerbaijan.png"],
    badge: "Honeymoon",
    title: "Baku Honeymoon",
    location: "Azerbaijan",
    duration: "05 Days / 04 Nights",
    price: "PKR 295,000",
    slug: "baku-honeymoon",
    category: "honeymoon",
    rating: 4.5,
    reviews: 58,
  },
  {
    images: ["/images/client/tours/Malaysia--Kuala-Lumpur-.png"],
    badge: "Honeymoon",
    title: "Malaysia Honeymoon",
    location: "Malaysia",
    duration: "06 Days / 05 Nights",
    price: "PKR 315,000",
    slug: "malaysia-honeymoon",
    category: "honeymoon",
    rating: 4.5,
    reviews: 66,
  },
  {
    images: ["/images/client/tours/Sri-Lanka.png"],
    badge: "Honeymoon",
    title: "Sri Lanka Honeymoon",
    location: "Sri Lanka",
    duration: "06 Days / 05 Nights",
    price: "PKR 305,000",
    slug: "sri-lanka-honeymoon",
    category: "honeymoon",
    rating: 4.6,
    reviews: 59,
  },
];

export const corporatePackages: Pkg[] = [
  {
    images: ["/images/client/tours/Dubai.png"],
    badge: "Corporate",
    title: "Dubai Corporate Retreat",
    location: "United Arab Emirates",
    duration: "05 Days / 04 Nights",
    price: "PKR 285,000",
    slug: "dubai-corporate-tour",
    category: "corporate",
    rating: 4.7,
    reviews: 48,
  },
  {
    images: ["/images/client/tours/Baku--Azerbaijan.png"],
    badge: "Corporate",
    title: "Baku Corporate Retreat",
    location: "Azerbaijan",
    duration: "05 Days / 04 Nights",
    price: "PKR 265,000",
    slug: "baku-corporate-tour",
    category: "corporate",
    rating: 4.5,
    reviews: 39,
  },
  {
    images: ["/images/client/tours/Bali--Indoneshia.png"],
    badge: "Corporate",
    title: "Bali Corporate Retreat",
    location: "Indonesia",
    duration: "06 Days / 05 Nights",
    price: "PKR 395,000",
    slug: "bali-corporate-tour",
    category: "corporate",
    rating: 4.6,
    reviews: 44,
  },
  {
    images: ["/images/client/tours/Malaysia--Kuala-Lumpur-.png"],
    badge: "Corporate",
    title: "Malaysia Corporate Tour",
    location: "Malaysia",
    duration: "06 Days / 05 Nights",
    price: "PKR 305,000",
    slug: "malaysia-corporate-tour",
    category: "corporate",
    rating: 4.5,
    reviews: 36,
  },
  {
    images: ["/images/client/tours/Thailand.png"],
    badge: "Corporate",
    title: "Thailand Corporate Tour",
    location: "Thailand",
    duration: "07 Days / 06 Nights",
    price: "PKR 325,000",
    slug: "thailand-corporate-tour",
    category: "corporate",
    rating: 4.6,
    reviews: 41,
  },
  {
    images: ["/images/client/tours/Turkey.png"],
    badge: "Corporate",
    title: "Turkey Corporate Retreat",
    location: "Turkey",
    duration: "07 Days / 06 Nights",
    price: "PKR 385,000",
    slug: "turkey-corporate-tour",
    category: "corporate",
    rating: 4.7,
    reviews: 52,
  },
  {
    images: ["/images/client/tours/Europe.png"],
    badge: "Corporate",
    title: "Europe Corporate Retreat",
    location: "Europe",
    duration: "09 Days / 08 Nights",
    price: "PKR 795,000",
    slug: "europe-corporate-tour",
    category: "corporate",
    rating: 4.8,
    reviews: 60,
  },
];

const tourImgMap: Record<string, string> = {
  Thailand: "/images/client/tours/Thailand.png",
  Malaysia: "/images/client/tours/Malaysia--Kuala-Lumpur-.png",
  Azerbaijan: "/images/client/tours/Baku--Azerbaijan.png",
  Turkey: "/images/client/tours/Turkey.png",
  Pakistan: "/images/client/tours/Pakistan-Customized-Tour.jfif",
  Indonesia: "/images/client/tours/Bali--Indoneshia.png",
  "Sri Lanka": "/images/client/tours/Sri-Lanka.png",
  Maldives: "/images/client/tours/Maldives.png",
  China: "/images/client/tours/China-Customized-Tour.png",
  Japan: "/images/client/tours/Japan-Customized-Tour.png",
  Qatar: "/images/client/tours/Qatar-Customized-Tour.png",
  Bahrain: "/images/client/tours/Bahrain-Customized-Tour.png",
  Uzbekistan: "/images/client/tours/Uzbekistan-Customized-Tour.webp",
  Egypt: "/images/client/tours/Egypt-Customized-Tour.jpg",
  Singapore: "/images/client/tours/Singapore-Customized-Tour.png",
  "Saudi Arabia": "/images/client/tours/Saudi-Arabia-Customized-Tour.png",
  Dubai: "/images/client/tours/Dubai.png",
  Cambodia: "/images/client/tours/Cambodia-Customized-Tour.jpg",
  Philippines: "/images/client/tours/Philippines-Customized-Tour.png",
  Vietnam: "/images/client/tours/Vietnam-Customized-Tour.png",
};

export const customizedPackages: Pkg[] = [
  "Thailand",
  "Malaysia",
  "Azerbaijan",
  "Turkey",
  "Pakistan",
  "Indonesia",
  "Sri Lanka",
  "Maldives",
  "China",
  "Japan",
  "Qatar",
  "Bahrain",
  "Uzbekistan",
  "Egypt",
  "Singapore",
  "Saudi Arabia",
  "Dubai",
  "Cambodia",
  "Philippines",
  "Vietnam",
].map((name, i): Pkg => ({
  images: [
    tourImgMap[name] ??
      `${IMG}/home1/tour-package-img${[6, 1, 11, 14, 13, 2, 4, 10, 7, 7, 8, 9, 15, 12, 3, 16, 8, 5, 17, 18][i]}.jpg`,
  ],
  badge: "Customized",
  title: `${name} Customized Tour`,
  location: name,
  duration: "06 Days / 05 Nights",
  price: `PKR ${[265, 245, 235, 385, 145, 395, 255, 495, 465, 625, 285, 275, 325, 425, 335, 355, 295, 315, 375, 365][i]},000`,
  slug: `customized-tour-${name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
  category: "customized",
  rating: 4.5,
  reviews: 30 + i,
}));

export const educationalPackages: Pkg[] = [
  {
    images: ["/images/client/tours/Spain.png"],
    badge: "Educational",
    title: "Spain Educational Tour",
    location: "Spain",
    duration: "07 Days / 06 Nights",
    price: "PKR 485,000",
    slug: "educational-tour-spain",
    category: "educational",
    rating: 4.7,
    reviews: 55,
  },
  {
    images: ["/images/client/tours/Thailand.png"],
    badge: "Educational",
    title: "Thailand Educational Tour",
    location: "Thailand",
    duration: "06 Days / 05 Nights",
    price: "PKR 295,000",
    slug: "educational-tour-thailand",
    category: "educational",
    rating: 4.5,
    reviews: 47,
  },
  {
    images: ["/images/client/tours/Australia.webp"],
    badge: "Educational",
    title: "Australia Educational Tour",
    location: "Australia",
    duration: "09 Days / 08 Nights",
    price: "PKR 645,000",
    slug: "educational-tour-australia",
    category: "educational",
    rating: 4.8,
    reviews: 62,
  },
  {
    images: ["/images/client/tours/Italy.avif"],
    badge: "Educational",
    title: "Italy Educational Tour",
    location: "Italy",
    duration: "07 Days / 06 Nights",
    price: "PKR 525,000",
    slug: "educational-tour-italy",
    category: "educational",
    rating: 4.6,
    reviews: 44,
  },
  {
    images: ["/images/client/tours/Egypt-Customized-Tour.jpg"],
    badge: "Educational",
    title: "Egypt Educational Tour",
    location: "Egypt",
    duration: "06 Days / 05 Nights",
    price: "PKR 385,000",
    slug: "educational-tour-egypt",
    category: "educational",
    rating: 4.4,
    reviews: 38,
  },
  {
    images: ["/images/client/tours/England.avif"],
    badge: "Educational",
    title: "England Educational Tour",
    location: "United Kingdom",
    duration: "07 Days / 06 Nights",
    price: "PKR 585,000",
    slug: "educational-tour-england",
    category: "educational",
    rating: 4.6,
    reviews: 51,
  },
  {
    images: ["/images/client/tours/Swedan.png"],
    badge: "Educational",
    title: "Sweden Educational Tour",
    location: "Sweden",
    duration: "07 Days / 06 Nights",
    price: "PKR 595,000",
    slug: "educational-tour-sweden",
    category: "educational",
    rating: 4.7,
    reviews: 40,
  },
  {
    images: ["/images/client/tours/Norway.jpg"],
    badge: "Educational",
    title: "Norway Educational Tour",
    location: "Norway",
    duration: "07 Days / 06 Nights",
    price: "PKR 615,000",
    slug: "educational-tour-norway",
    category: "educational",
    rating: 4.8,
    reviews: 57,
  },
];

export const tourPackages: Pkg[] = [
  ...groupTourPackages,
  ...honeymoonPackages,
  ...corporatePackages,
  ...customizedPackages,
  ...educationalPackages,
];

export const allPackages: Pkg[] = [
  ...popularPackages,
  ...oneDayTrips,
  ...lastMinuteDeals,
  ...destinationPackages.filter(
    (p) => ![...popularPackages, ...oneDayTrips, ...lastMinuteDeals].some((x) => x.slug === p.slug),
  ),
  ...tourPackages.filter(
    (p) =>
      ![...popularPackages, ...oneDayTrips, ...lastMinuteDeals, ...destinationPackages].some(
        (x) => x.slug === p.slug,
      ),
  ),
];

export type PackageDetail = {
  slug: string;
  rating: number;
  reviews: number;
  destinations: string[];
  description: string;
  tourType: string;
  groupSize: string;
  info: { label: string; value: string }[];
  locations: { img: string; title: string; days: string }[];
  highlights: string[];
  itinerary: {
    day: string;
    title: string;
    desc: string;
    transport: string;
    activities: string;
    meals: string;
    accommodation: string;
  }[];
  includes: string[];
  excludes: string[];
  additionalInfo: string[];
  faqs: { q: string; a: string }[];
};

export const packageDetails: Record<string, PackageDetail> = {
  "maldives-beach-paradise": {
    slug: "maldives-beach-paradise",
    rating: 4.5,
    reviews: 134,
    destinations: ["Malé", "Baa Atoll", "Maafushi"],
    description:
      "Escape to the turquoise waters and powdery white sands of the Maldives. This all-inclusive beach paradise package combines overwater villas, world-class snorkelling and unforgettable sunset cruises for a truly relaxing island getaway.",
    tourType: "Honeymoon Tour",
    groupSize: "02-08",
    info: [
      { label: "Accommodation", value: "Overwater Villa" },
      { label: "Meals", value: "All-Inclusive" },
      { label: "Transportation", value: "Seaplane, Speedboat" },
      { label: "Group Size", value: "02-08" },
      { label: "Language", value: "English" },
      { label: "Age Range", value: "16-60 (Year)" },
      { label: "Season", value: "All Season" },
      { label: "Category", value: "Honeymoon, Beach" },
    ],
    locations: [
      {
        img: `${IMG}/innerpages/package-dt-location-img1.jpg`,
        title: "Malé Atoll",
        days: "01 Days",
      },
      {
        img: `${IMG}/innerpages/package-dt-location-img2.jpg`,
        title: "Baa Atoll",
        days: "02 Days",
      },
      {
        img: `${IMG}/innerpages/package-dt-location-img3.jpg`,
        title: "Maafushi Island",
        days: "02 Days",
      },
    ],
    highlights: [
      "Stay in a luxurious overwater villa with direct lagoon access.",
      "Snorkelling & diving among vibrant coral reefs and manta rays.",
      "Romantic sunset cruise with dinner under the stars.",
      "Private candlelight dinner on a sandbank.",
      "Traditional Boduberu music & island hopping excursion.",
    ],
    itinerary: [
      {
        day: "Day-01",
        title: "Arrival in Malé & Seaplane to Resort",
        desc: "Arrive at Malé International Airport and transfer by seaplane to your overwater villa. Relax on the beach and enjoy a welcome dinner at the resort's finest restaurant.",
        transport: "Seaplane, Speedboat",
        activities: "Arrival transfer, Beach time, Welcome dinner",
        meals: "Breakfast, Dinner",
        accommodation: "Overwater Villa",
      },
      {
        day: "Day-02",
        title: "Snorkelling & Dolphin Cruise",
        desc: "Start the day with a guided snorkelling session at the house reef, then head out on a sunset dolphin cruise where spinner dolphins leap alongside the boat.",
        transport: "Boat",
        activities: "Snorkelling, Dolphin cruise",
        meals: "Breakfast, Lunch, Dinner",
        accommodation: "Overwater Villa",
      },
      {
        day: "Day-03",
        title: "Baa Atoll UNESCO Excursion",
        desc: "A full day excursion to the UNESCO Biosphere Reserve of Baa Atoll — swim with manta rays, enjoy a sandbank picnic and explore a local fishing village.",
        transport: "Speedboat",
        activities: "Manta ray swim, Sandbank picnic",
        meals: "Breakfast, Lunch",
        accommodation: "Overwater Villa",
      },
      {
        day: "Day-04",
        title: "Leisure Day & Spa",
        desc: "A free day to enjoy the resort's amenities — spa treatments, water sports, infinity pool and sunset cocktails by the beach.",
        transport: "–",
        activities: "Spa, Water sports, Pool time",
        meals: "Breakfast, Dinner",
        accommodation: "Overwater Villa",
      },
      {
        day: "Day-05",
        title: "Departure",
        desc: "Enjoy a final breakfast at the lagoon restaurant before transferring back to Malé International Airport for your onward journey.",
        transport: "Speedboat, Seaplane",
        activities: "Departure transfer",
        meals: "Breakfast",
        accommodation: "–",
      },
    ],
    includes: [
      "Overwater villa accommodation with daily housekeeping.",
      "All-Inclusive meals (Breakfast, Lunch, Dinner).",
      "Return seaplane & speedboat transfers.",
      "Snorkelling gear & house reef access.",
      "Sunset dolphin cruise & island hopping.",
      "Travel assistance 24/7.",
    ],
    excludes: [
      "International flights.",
      "Visa fees & processing.",
      "Personal expenses (shopping, spa, tips).",
      "Optional scuba diving certification.",
      "Travel insurance (if not added).",
    ],
    additionalInfo: [
      "Free cancellation – up to 48 hours before departure.",
      "Health & safety guidelines – COVID-19 regulations may apply.",
      "Passport must be valid for at least 6 months.",
    ],
    faqs: [
      {
        q: "Is the seaplane transfer included?",
        a: "Yes, return seaplane transfers between Malé and the resort are fully included in this package.",
      },
      {
        q: "Can we add scuba diving?",
        a: "Absolutely. We offer optional scuba diving sessions and certification courses at an additional cost.",
      },
      {
        q: "What is the best time to visit the Maldives?",
        a: "November to April offers the best weather with clear skies and calm seas.",
      },
      {
        q: "Is this package suitable for families?",
        a: "Yes, the resort offers kids clubs and family activities, though the package is most popular with couples.",
      },
    ],
  },
  "bali-paradise-tour": {
    slug: "bali-paradise-tour",
    rating: 4.6,
    reviews: 98,
    destinations: ["Ubud", "Seminyak", "Uluwatu"],
    description:
      "Discover the Island of the Gods on this 7-day journey through lush rice terraces, ancient temples and golden beaches. A perfect blend of culture, adventure and pure relaxation in Bali.",
    tourType: "Group Tour",
    groupSize: "10-20",
    info: [
      { label: "Accommodation", value: "4 Star Resort" },
      { label: "Meals", value: "Breakfast & Dinner" },
      { label: "Transportation", value: "Private Car, Boat" },
      { label: "Group Size", value: "10-20" },
      { label: "Language", value: "English" },
      { label: "Age Range", value: "18-55 (Year)" },
      { label: "Season", value: "All Season" },
      { label: "Category", value: "Adventure, Culture" },
    ],
    locations: [
      { img: `${IMG}/innerpages/package-dt-location-img1.jpg`, title: "Ubud", days: "02 Days" },
      { img: `${IMG}/innerpages/package-dt-location-img2.jpg`, title: "Seminyak", days: "02 Days" },
      { img: `${IMG}/innerpages/package-dt-location-img3.jpg`, title: "Uluwatu", days: "03 Days" },
    ],
    highlights: [
      "Sunrise trek up Mount Batur volcano.",
      "Guided tour of the Tegallalang rice terraces.",
      "Visit to the sacred Uluwatu Temple & Kecak fire dance.",
      "Snorkelling at Nusa Penida with manta rays.",
      "Traditional Balinese cooking class in Ubud.",
    ],
    itinerary: [
      {
        day: "Day-01",
        title: "Arrival in Bali & Ubud",
        desc: "Arrive at Ngurah Rai Airport and transfer to Ubud. Enjoy an orientation walk through the artisan town and a welcome dinner with live Balinese dance.",
        transport: "Private Car",
        activities: "Arrival transfer, Orientation walk",
        meals: "Dinner",
        accommodation: "Ubud Resort",
      },
      {
        day: "Day-02",
        title: "Tegallalang Terraces & Temples",
        desc: "Explore the emerald rice terraces of Tegallalang, visit the Sacred Monkey Forest and tour the ancient Goa Gajah Elephant Cave.",
        transport: "Private Car",
        activities: "Terraces, Monkey Forest, Goa Gajah",
        meals: "Breakfast, Lunch",
        accommodation: "Ubud Resort",
      },
      {
        day: "Day-03",
        title: "Mount Batur Sunrise Trek",
        desc: "A pre-dawn trek to the summit of Mount Batur to witness a spectacular sunrise over the caldera and Lake Batur, followed by a natural hot spring soak.",
        transport: "Private Car, Trek",
        activities: "Sunrise trek, Hot springs",
        meals: "Breakfast, Lunch",
        accommodation: "Ubud Resort",
      },
      {
        day: "Day-04",
        title: "Nusa Penida Island Day Trip",
        desc: "Speedboat to Nusa Penida for snorkelling with manta rays, visiting Kelingking Beach and the famous Broken Beach.",
        transport: "Speedboat, Van",
        activities: "Snorkelling, Island sightseeing",
        meals: "Breakfast, Lunch",
        accommodation: "Seminyak Resort",
      },
      {
        day: "Day-05",
        title: "Uluwatu Temple & Fire Dance",
        desc: "Travel to the clifftop Uluwatu Temple for sunset and the mesmerizing Kecak fire dance, with dinner at Jimbaran Bay.",
        transport: "Private Car",
        activities: "Temple, Fire dance, Beach dinner",
        meals: "Breakfast, Dinner",
        accommodation: "Seminyak Resort",
      },
      {
        day: "Day-06",
        title: "Leisure Day & Cooking Class",
        desc: "A relaxed day — optional Balinese cooking class, spa treatments and beach time at Seminyak.",
        transport: "–",
        activities: "Cooking class, Spa, Beach",
        meals: "Breakfast",
        accommodation: "Seminyak Resort",
      },
      {
        day: "Day-07",
        title: "Departure",
        desc: "Transfer to Ngurah Rai Airport for your departure flight with memories of the Island of the Gods.",
        transport: "Private Car",
        activities: "Departure transfer",
        meals: "Breakfast",
        accommodation: "–",
      },
    ],
    includes: [
      "4 Star resort accommodation.",
      "Daily breakfast & selected dinners.",
      "Private air-conditioned transport.",
      "Nusa Penida speedboat & snorkelling gear.",
      "Entry tickets to temples & attractions.",
      "English-speaking tour guide.",
    ],
    excludes: [
      "International flights.",
      "Visa fees & processing.",
      "Personal expenses (shopping, tips).",
      "Optional spa treatments.",
      "Travel insurance.",
    ],
    additionalInfo: [
      "Free cancellation – up to 72 hours before departure.",
      "Comfortable walking shoes recommended for temple visits.",
      "Moderate fitness required for the Mount Batur trek.",
    ],
    faqs: [
      {
        q: "How fit do I need to be for the Batur trek?",
        a: "A moderate level of fitness is required; the trek takes about 2 hours each way and is suitable for most healthy travelers.",
      },
      {
        q: "Are temple entry fees included?",
        a: "Yes, all entry tickets listed in the itinerary are included in the package price.",
      },
      {
        q: "Can I extend my stay in Bali?",
        a: "Yes, we can customize your package to add extra nights at any of our partner resorts.",
      },
    ],
  },
  "phuket-krabi-island": {
    slug: "phuket-krabi-island",
    rating: 4.4,
    reviews: 76,
    destinations: ["Phuket", "Krabi", "Phi Phi Islands"],
    description:
      "Hop between the stunning limestone islands of southern Thailand on this 10-day adventure. White-sand beaches, emerald lagoons and vibrant nightlife make this a tropical favourite.",
    tourType: "Group Tour",
    groupSize: "12-20",
    info: [
      { label: "Accommodation", value: "4 Star Beach Resort" },
      { label: "Meals", value: "Breakfast & Dinner" },
      { label: "Transportation", value: "Car, Longtail Boat" },
      { label: "Group Size", value: "12-20" },
      { label: "Language", value: "English" },
      { label: "Age Range", value: "18-60 (Year)" },
      { label: "Season", value: "November - March" },
      { label: "Category", value: "Beach, Adventure" },
    ],
    locations: [
      { img: `${IMG}/innerpages/package-dt-location-img1.jpg`, title: "Phuket", days: "03 Days" },
      {
        img: `${IMG}/innerpages/package-dt-location-img2.jpg`,
        title: "Phi Phi Islands",
        days: "02 Days",
      },
      { img: `${IMG}/innerpages/package-dt-location-img3.jpg`, title: "Krabi", days: "05 Days" },
    ],
    highlights: [
      "Longtail boat cruise around Phi Phi Leh's Maya Bay.",
      "Snorkelling in the crystal-clear waters of Bamboo Island.",
      "Explore the Tiger Cave Temple and Railay Beach.",
      "Visit the Big Buddha and Phuket Old Town.",
      "Sunset dinner cruise in Phang Nga Bay.",
    ],
    itinerary: [
      {
        day: "Day-01",
        title: "Arrival in Phuket",
        desc: "Arrive at Phuket International Airport and transfer to your beachfront resort. Evening welcome dinner with Thai cultural show.",
        transport: "Private Van",
        activities: "Arrival transfer, Welcome dinner",
        meals: "Dinner",
        accommodation: "Phuket Resort",
      },
      {
        day: "Day-02",
        title: "Phuket Big Buddha & Old Town",
        desc: "Visit the majestic Big Buddha and enjoy a walking tour of Phuket Old Town's colourful Sino-Portuguese architecture and local markets.",
        transport: "Private Van",
        activities: "Big Buddha, Old Town tour",
        meals: "Breakfast, Lunch",
        accommodation: "Phuket Resort",
      },
      {
        day: "Day-03",
        title: "Phi Phi Islands Day Cruise",
        desc: "Full-day speedboat cruise to Phi Phi Leh, Maya Bay, Pileh Lagoon and Bamboo Island with snorkelling and a beachside BBQ lunch.",
        transport: "Speedboat",
        activities: "Maya Bay, Snorkelling, Lagoon",
        meals: "Breakfast, Lunch",
        accommodation: "Phuket Resort",
      },
      {
        day: "Day-04",
        title: "Phang Nga Bay & James Bond Island",
        desc: "Cruise the limestone karsts of Phang Nga Bay, paddle a sea cave and see the iconic James Bond Island.",
        transport: "Longtail Boat",
        activities: "Island cruise, Sea canoeing",
        meals: "Breakfast, Lunch",
        accommodation: "Phuket Resort",
      },
      {
        day: "Day-05",
        title: "Transfer to Krabi",
        desc: "Scenic drive to Krabi. Afternoon free time at Ao Nang beach with sunset views over Railay.",
        transport: "Private Van",
        activities: "Transfer, Ao Nang beach",
        meals: "Breakfast",
        accommodation: "Krabi Resort",
      },
      {
        day: "Day-06",
        title: "Railay & Tiger Cave Temple",
        desc: "Longtail boat to Railay Beach for rock climbing and lagoon hikes, then climb the Tiger Cave Temple for panoramic views.",
        transport: "Longtail Boat, Van",
        activities: "Railay, Tiger Cave, Climbing",
        meals: "Breakfast, Lunch",
        accommodation: "Krabi Resort",
      },
      {
        day: "Day-07",
        title: "Hong Islands Tour",
        desc: "Day trip to the pristine Hong Islands — kayak through hidden lagoons and snorkel among vibrant coral gardens.",
        transport: "Speedboat",
        activities: "Hong Islands, Kayaking, Snorkel",
        meals: "Breakfast, Lunch",
        accommodation: "Krabi Resort",
      },
      {
        day: "Day-08",
        title: "Emerald Pool & Hot Springs",
        desc: "Visit the emerald pool and crystal lagoon in Khao Sok's rainforest, followed by natural hot springs.",
        transport: "Private Van",
        activities: "Emerald Pool, Hot springs",
        meals: "Breakfast, Lunch",
        accommodation: "Krabi Resort",
      },
      {
        day: "Day-09",
        title: "Leisure Day",
        desc: "Free day to relax by the pool, explore Krabi Town's night market or book optional island excursions.",
        transport: "–",
        activities: "Free time, Night market",
        meals: "Breakfast",
        accommodation: "Krabi Resort",
      },
      {
        day: "Day-10",
        title: "Departure",
        desc: "Transfer to Krabi International Airport for your onward flight.",
        transport: "Private Van",
        activities: "Departure transfer",
        meals: "Breakfast",
        accommodation: "–",
      },
    ],
    includes: [
      "Beach resort accommodation.",
      "Daily breakfast & selected meals.",
      "All island speedboat & longtail boat trips.",
      "Snorkelling equipment.",
      "Entry tickets & national park fees.",
      "English-speaking guide.",
    ],
    excludes: [
      "International flights.",
      "Visa fees & processing.",
      "Personal expenses (shopping, tips).",
      "Optional rock climbing gear.",
      "Travel insurance.",
    ],
    additionalInfo: [
      "Free cancellation – up to 72 hours before departure.",
      "Best visited between November and March for calm seas.",
      "Please bring reef-safe sunscreen.",
    ],
    faqs: [
      {
        q: "Are the island tours suitable for children?",
        a: "Yes, most island tours are family friendly with life jackets available on all boats.",
      },
      {
        q: "Do I need experience to go sea canoeing?",
        a: "No experience needed — a local paddler guides your canoe through the caves.",
      },
    ],
  },
  "rome-florence-venice": {
    slug: "rome-florence-venice",
    rating: 4.8,
    reviews: 156,
    destinations: ["Rome", "Florence", "Venice"],
    description:
      "Trace the footsteps of emperors, artists and romantics on this classic Italian journey. From the Colosseum to the canals of Venice, experience the best of Italy in one unforgettable trip.",
    tourType: "Private Tour",
    groupSize: "10-15",
    info: [
      { label: "Accommodation", value: "4 Star Hotel" },
      { label: "Meals", value: "Breakfast & Dinner" },
      { label: "Transportation", value: "Car, High-speed Train" },
      { label: "Group Size", value: "10-15" },
      { label: "Language", value: "English, Italian" },
      { label: "Age Range", value: "12-70 (Year)" },
      { label: "Season", value: "April - October" },
      { label: "Category", value: "Culture, History" },
    ],
    locations: [
      { img: `${IMG}/innerpages/package-dt-location-img1.jpg`, title: "Rome", days: "03 Days" },
      { img: `${IMG}/innerpages/package-dt-location-img2.jpg`, title: "Florence", days: "02 Days" },
      { img: `${IMG}/innerpages/package-dt-location-img3.jpg`, title: "Venice", days: "02 Days" },
    ],
    highlights: [
      "Skip-the-line entry to the Colosseum & Roman Forum.",
      "Vatican Museums and the Sistine Chapel with expert guide.",
      "Climb the Duomo in Florence & see Michelangelo's David.",
      "Gondola ride through the canals of Venice.",
      "Wine tasting in the Tuscan countryside.",
    ],
    itinerary: [
      {
        day: "Day-01",
        title: "Arrival in Rome",
        desc: "Arrive in Rome and transfer to your central hotel. Evening walking tour of Piazza Navona, Pantheon and Trevi Fountain.",
        transport: "Private Car",
        activities: "Arrival transfer, Evening walk",
        meals: "Dinner",
        accommodation: "Rome Hotel",
      },
      {
        day: "Day-02",
        title: "Colosseum & Ancient Rome",
        desc: "Skip-the-line guided tour of the Colosseum, Roman Forum and Palatine Hill with a local historian.",
        transport: "Walk, Metro",
        activities: "Colosseum, Roman Forum",
        meals: "Breakfast, Lunch",
        accommodation: "Rome Hotel",
      },
      {
        day: "Day-03",
        title: "Vatican & St. Peter's Basilica",
        desc: "Early-access tour of the Vatican Museums, Raphael Rooms and Sistine Chapel, then visit St. Peter's Basilica.",
        transport: "Walk, Metro",
        activities: "Vatican Museums, Sistine Chapel",
        meals: "Breakfast, Lunch",
        accommodation: "Rome Hotel",
      },
      {
        day: "Day-04",
        title: "High-Speed Train to Florence",
        desc: "Travel by high-speed train to Florence. Afternoon guided walk through the Duomo, Piazza della Signoria and Ponte Vecchio.",
        transport: "High-speed Train",
        activities: "Duomo, Piazza della Signoria",
        meals: "Breakfast, Dinner",
        accommodation: "Florence Hotel",
      },
      {
        day: "Day-05",
        title: "Uffizi & Michelangelo's David",
        desc: "Guided visit to the Accademia to see Michelangelo's David and the Uffizi Gallery's Renaissance masterpieces. Afternoon Tuscan wine tasting.",
        transport: "Walk",
        activities: "Accademia, Uffizi, Wine tasting",
        meals: "Breakfast, Lunch",
        accommodation: "Florence Hotel",
      },
      {
        day: "Day-06",
        title: "Train to Venice & Gondola Ride",
        desc: "Scenic train through Tuscany to Venice. Evening gondola ride through the Grand Canal and St. Mark's Square.",
        transport: "High-speed Train, Gondola",
        activities: "Gondola, St. Mark's Square",
        meals: "Breakfast, Dinner",
        accommodation: "Venice Hotel",
      },
      {
        day: "Day-07",
        title: "St. Mark's & Murano Glass",
        desc: "Visit St. Mark's Basilica and the Doge's Palace, then take a boat to Murano for a glass-blowing demonstration.",
        transport: "Vaporetto, Boat",
        activities: "Basilica, Doge's Palace, Murano",
        meals: "Breakfast, Lunch",
        accommodation: "Venice Hotel",
      },
      {
        day: "Day-08",
        title: "Departure",
        desc: "Water taxi to Venice airport for your departure, or continue your Italian adventure on request.",
        transport: "Water Taxi",
        activities: "Departure transfer",
        meals: "Breakfast",
        accommodation: "–",
      },
    ],
    includes: [
      "4 star hotel accommodation.",
      "Daily breakfast & selected dinners.",
      "High-speed train between cities.",
      "Skip-the-line entry tickets & guided tours.",
      "Gondola ride & Murano visit.",
      "Wine tasting experience.",
    ],
    excludes: [
      "International flights.",
      "Visa fees & processing.",
      "City tax (payable at hotels).",
      "Personal expenses (shopping, tips).",
      "Travel insurance.",
    ],
    additionalInfo: [
      "Free cancellation – up to 7 days before departure.",
      "Dress modestly when visiting religious sites.",
      "April to October offers the best weather.",
    ],
    faqs: [
      {
        q: "Do I need to dress a certain way for the Vatican?",
        a: "Yes, shoulders and knees must be covered when entering St. Peter's Basilica.",
      },
      {
        q: "Is the high-speed train comfortable for families?",
        a: "Absolutely — trains feature spacious seats, dining cars and luggage storage.",
      },
      {
        q: "Can we add a day trip to Pompeii?",
        a: "Yes, a day trip to Pompeii from Rome can be added to this itinerary.",
      },
    ],
  },
  "egypt-nile-cruise-adventure": {
    slug: "egypt-nile-cruise-adventure",
    rating: 4.3,
    reviews: 64,
    destinations: ["Cairo", "Luxor", "Aswan"],
    description:
      "Sail the legendary Nile on this 10-day adventure through the land of the Pharaohs. Pyramids, temples and majestic river cruises make this an unforgettable journey into ancient history.",
    tourType: "Group Tour",
    groupSize: "15-25",
    info: [
      { label: "Accommodation", value: "5 Star Hotel & Nile Cruise" },
      { label: "Meals", value: "Full Board" },
      { label: "Transportation", value: "Car, Cruise Ship" },
      { label: "Group Size", value: "15-25" },
      { label: "Language", value: "English" },
      { label: "Age Range", value: "12-70 (Year)" },
      { label: "Season", value: "October - April" },
      { label: "Category", value: "History, Adventure" },
    ],
    locations: [
      { img: `${IMG}/innerpages/package-dt-location-img1.jpg`, title: "Cairo", days: "03 Days" },
      { img: `${IMG}/innerpages/package-dt-location-img2.jpg`, title: "Luxor", days: "03 Days" },
      { img: `${IMG}/innerpages/package-dt-location-img3.jpg`, title: "Aswan", days: "04 Days" },
    ],
    highlights: [
      "Sunrise camel ride to the Great Pyramids of Giza.",
      "Guided tour of the Egyptian Museum & the treasures of Tutankhamun.",
      "Luxor's Valley of the Kings and Karnak Temple.",
      "Felucca ride and Temple of Philae in Aswan.",
      "4-night luxury Nile cruise with onboard entertainment.",
    ],
    itinerary: [
      {
        day: "Day-01",
        title: "Arrival in Cairo",
        desc: "Arrive at Cairo International Airport, meet your Egyptologist guide and transfer to your hotel. Evening welcome dinner overlooking the Nile.",
        transport: "Private Van",
        activities: "Arrival transfer, Welcome dinner",
        meals: "Dinner",
        accommodation: "Cairo Hotel",
      },
      {
        day: "Day-02",
        title: "Great Pyramids of Giza",
        desc: "Full day at the Giza Plateau — explore the Great Pyramid, Sphinx and Solar Boat Museum, with an optional sunrise camel ride.",
        transport: "Private Van",
        activities: "Pyramids, Sphinx, Camel ride",
        meals: "Breakfast, Lunch",
        accommodation: "Cairo Hotel",
      },
      {
        day: "Day-03",
        title: "Egyptian Museum & Khan el-Khalili",
        desc: "Morning at the Egyptian Museum, then browse the vibrant Khan el-Khalili bazaar in old Islamic Cairo.",
        transport: "Private Van",
        activities: "Museum, Khan el-Khalili",
        meals: "Breakfast, Lunch",
        accommodation: "Cairo Hotel",
      },
      {
        day: "Day-04",
        title: "Fly to Luxor & Embark Cruise",
        desc: "Morning flight to Luxor, tour the Karnak Temple complex and the Avenue of Sphinxes, then board your Nile cruise ship.",
        transport: "Flight, Cruise Ship",
        activities: "Karnak Temple, Board cruise",
        meals: "Breakfast, Lunch, Dinner",
        accommodation: "Nile Cruise",
      },
      {
        day: "Day-05",
        title: "Valley of the Kings & Hatshepsut",
        desc: "Sail the Nile while touring the Valley of the Kings, Colossi of Memnon and the majestic temple of Queen Hatshepsut at Deir el-Bahri.",
        transport: "Cruise Ship, Van",
        activities: "Valley of Kings, Hatshepsut Temple",
        meals: "Breakfast, Lunch, Dinner",
        accommodation: "Nile Cruise",
      },
      {
        day: "Day-06",
        title: "Edfu & Kom Ombo Temples",
        desc: "Visit the best-preserved Ptolemaic temple of Horus at Edfu, then the twin temple of Sobek and Haroeris at Kom Ombo.",
        transport: "Cruise Ship",
        activities: "Edfu Temple, Kom Ombo",
        meals: "Breakfast, Lunch, Dinner",
        accommodation: "Nile Cruise",
      },
      {
        day: "Day-07",
        title: "Aswan High Dam & Philae Temple",
        desc: "Explore the Aswan High Dam, the granite quarries of the Unfinished Obelisk and the romantic Temple of Philae on Agilkia Island.",
        transport: "Van, Boat",
        activities: "High Dam, Philae Temple",
        meals: "Breakfast, Lunch, Dinner",
        accommodation: "Nile Cruise",
      },
      {
        day: "Day-08",
        title: "Felucca & Nubian Village",
        desc: "Glide on a traditional felucca around Elephantine Island and visit a colourful Nubian village to learn about local culture.",
        transport: "Felucca",
        activities: "Felucca ride, Nubian village",
        meals: "Breakfast, Lunch",
        accommodation: "Aswan Hotel",
      },
      {
        day: "Day-09",
        title: "Flight Back to Cairo",
        desc: "Morning flight back to Cairo. Afternoon free for last-minute shopping or an optional tour of Saqqara and the Step Pyramid.",
        transport: "Flight, Van",
        activities: "Flight, Optional Saqqara",
        meals: "Breakfast, Dinner",
        accommodation: "Cairo Hotel",
      },
      {
        day: "Day-10",
        title: "Departure",
        desc: "Transfer to Cairo International Airport for your departure flight, taking home memories of the land of the Pharaohs.",
        transport: "Private Van",
        activities: "Departure transfer",
        meals: "Breakfast",
        accommodation: "–",
      },
    ],
    includes: [
      "5 star hotels & 4-night Nile cruise.",
      "Full board meals on cruise, breakfast elsewhere.",
      "Internal flights Cairo – Luxor / Aswan – Cairo.",
      "All guided tours with Egyptologist.",
      "Entry tickets to all mentioned sites.",
      "Camel ride & felucca experience.",
    ],
    excludes: [
      "International flights.",
      "Visa fees & processing.",
      "Personal expenses (shopping, tips).",
      "Optional balloon flight over Luxor.",
      "Travel insurance.",
    ],
    additionalInfo: [
      "Free cancellation – up to 7 days before departure.",
      "Best visited between October and April.",
      "Comfortable, modest clothing recommended for sites.",
    ],
    faqs: [
      {
        q: "Is the hot air balloon ride over Luxor included?",
        a: "No, the sunrise balloon flight is an optional add-on available at booking.",
      },
      {
        q: "How long do we actually spend on the cruise?",
        a: "You spend 4 nights aboard the Nile cruise between Luxor and Aswan.",
      },
      {
        q: "Is this package suitable for older travelers?",
        a: "Yes, most sightseeing is gentle, though some temple steps require moderate mobility.",
      },
    ],
  },
  "norway-northern-lights": {
    slug: "norway-northern-lights",
    rating: 4.9,
    reviews: 210,
    destinations: ["Oslo", "Tromsø", "Lofoten Islands"],
    description:
      "Chase the magical aurora borealis across Arctic Norway. This winter adventure combines dog-sledding, fjords and cosy glass igloos under the dancing northern lights.",
    tourType: "Adventure Tour",
    groupSize: "08-14",
    info: [
      { label: "Accommodation", value: "Glass Igloo & Lodge" },
      { label: "Meals", value: "Breakfast & Dinner" },
      { label: "Transportation", value: "Car, Ferry, Snowmobile" },
      { label: "Group Size", value: "08-14" },
      { label: "Language", value: "English" },
      { label: "Age Range", value: "16-65 (Year)" },
      { label: "Season", value: "October - March" },
      { label: "Category", value: "Adventure, Winter" },
    ],
    locations: [
      { img: `${IMG}/innerpages/package-dt-location-img1.jpg`, title: "Tromsø", days: "03 Days" },
      {
        img: `${IMG}/innerpages/package-dt-location-img2.jpg`,
        title: "Lofoten Islands",
        days: "03 Days",
      },
      { img: `${IMG}/innerpages/package-dt-location-img3.jpg`, title: "Oslo", days: "01 Days" },
    ],
    highlights: [
      "Two dedicated northern lights chase nights.",
      "Dog-sledding across snow-covered valleys.",
      "Stay in a heated glass-roof aurora igloo.",
      "Snowmobile safari & ice fishing on a frozen lake.",
      "Sami culture experience with a reindeer sled ride.",
    ],
    itinerary: [
      {
        day: "Day-01",
        title: "Arrival in Tromsø",
        desc: "Arrive at Tromsø, the 'Gateway to the Arctic'. City tour of the Arctic Cathedral, then an evening northern lights chase.",
        transport: "Private Van",
        activities: "City tour, Aurora chase",
        meals: "Dinner",
        accommodation: "Arctic Lodge",
      },
      {
        day: "Day-02",
        title: "Dog-Sledding Adventure",
        desc: "Mush your own team of huskies through snowy trails, with lunch around a campfire in a traditional lavvu tent.",
        transport: "Van, Dogsled",
        activities: "Dog-sledding, Campfire lunch",
        meals: "Breakfast, Lunch, Dinner",
        accommodation: "Arctic Lodge",
      },
      {
        day: "Day-03",
        title: "Snowmobile Safari & Ice Fishing",
        desc: "Ride snowmobiles across the frozen fjords to a remote ice fishing spot, then warm up with a hot drink and grilled lunch.",
        transport: "Snowmobile",
        activities: "Snowmobile, Ice fishing",
        meals: "Breakfast, Lunch",
        accommodation: "Aurora Igloo",
      },
      {
        day: "Day-04",
        title: "Reindeer & Sami Culture",
        desc: "Meet the indigenous Sami people, ride a reindeer sled and learn about Arctic traditions over a warm meal in a Sami camp.",
        transport: "Private Van",
        activities: "Reindeer sled, Sami camp",
        meals: "Breakfast, Lunch, Dinner",
        accommodation: "Aurora Igloo",
      },
      {
        day: "Day-05",
        title: "Ferry to Lofoten Islands",
        desc: "Scenic ferry through the fjords to the dramatic Lofoten archipelago. Evening aurora photography session at a secluded beach.",
        transport: "Ferry, Van",
        activities: "Ferry crossing, Aurora photo",
        meals: "Breakfast, Dinner",
        accommodation: "Lofoten Lodge",
      },
      {
        day: "Day-06",
        title: "Lofoten Villages & Sea Eagle Safari",
        desc: "Explore the charming fishing villages of Reine and Å, then take a rib boat safari to spot sea eagles and maybe whales.",
        transport: "Van, Rib Boat",
        activities: "Village tour, Sea eagle safari",
        meals: "Breakfast, Lunch",
        accommodation: "Lofoten Lodge",
      },
      {
        day: "Day-07",
        title: "Return to Oslo",
        desc: "Fly back to Oslo via Tromsø. Afternoon free to explore the Opera House and visit the Viking Ship Museum.",
        transport: "Flight, Tram",
        activities: "Oslo sightseeing",
        meals: "Breakfast",
        accommodation: "Oslo Hotel",
      },
    ],
    includes: [
      "Accommodation incl. glass-roof aurora igloo.",
      "Daily breakfast & most dinners.",
      "Aurora chase tours with expert guides.",
      "Dog-sledding, snowmobile & reindeer sled.",
      "Ferry & rib boat safari.",
      "Thermal winter clothing rental.",
    ],
    excludes: [
      "International flights.",
      "Visa fees & processing.",
      "Personal expenses (shopping, tips).",
      "Travel insurance.",
      "Meals not listed in itinerary.",
    ],
    additionalInfo: [
      "Free cancellation – up to 14 days before departure.",
      "Aurora sightings depend on weather; we provide up to 2 chase nights.",
      "Dress in warm layers; thermal suits are provided.",
    ],
    faqs: [
      {
        q: "Am I guaranteed to see the northern lights?",
        a: "No lights can be 100% guaranteed, but two chase nights and clear-winter locations give you a high probability.",
      },
      {
        q: "Do I need prior experience for dog-sledding?",
        a: "No — our mushers teach you everything, and you can also ride as a passenger.",
      },
      {
        q: "How cold does it get?",
        a: "Temperatures range from -5°C to -20°C; thermal suits are provided.",
      },
    ],
  },
  "hanoi-kiem-lake": {
    slug: "hanoi-kiem-lake",
    rating: 4.4,
    reviews: 41,
    destinations: ["Hanoi"],
    description:
      "A perfect one-day escape through the charming streets of Hanoi's Old Quarter, starting with the serene Hoan Kiem Lake, hidden temples and a spectacular water puppet show.",
    tourType: "City Tour",
    groupSize: "05-15",
    info: [
      { label: "Accommodation", value: "Not Included" },
      { label: "Meals", value: "Lunch" },
      { label: "Transportation", value: "Taxi, Walking" },
      { label: "Group Size", value: "05-15" },
      { label: "Language", value: "English" },
      { label: "Age Range", value: "All Ages" },
      { label: "Season", value: "All Season" },
      { label: "Category", value: "City, Culture" },
    ],
    locations: [
      {
        img: `${IMG}/innerpages/package-dt-location-img1.jpg`,
        title: "Hoan Kiem Lake",
        days: "01 Day",
      },
      {
        img: `${IMG}/innerpages/package-dt-location-img2.jpg`,
        title: "Old Quarter",
        days: "01 Day",
      },
    ],
    highlights: [
      "Morning walk around the legendary Hoan Kiem Lake.",
      "Visit Ngoc Son Temple and the red Huc Bridge.",
      "Street food lunch tour of the Old Quarter.",
      "Traditional water puppet theatre show.",
      "Local coffee break at a hidden café.",
    ],
    itinerary: [
      {
        day: "Day-01",
        title: "Hanoi City Discovery",
        desc: "Start at Hoan Kiem Lake, cross the Huc Bridge to Ngoc Son Temple, explore the Old Quarter's 36 streets, enjoy a street food lunch and finish with a water puppet show.",
        transport: "Taxi, Walking",
        activities: "Lake walk, Temples, Food tour",
        meals: "Lunch",
        accommodation: "Not Included",
      },
    ],
    includes: [
      "English-speaking local guide.",
      "Street food lunch.",
      "Water puppet show ticket.",
      "Ngoc Son Temple entry.",
      "Local transportation during the tour.",
    ],
    excludes: [
      "Hotel accommodation.",
      "Personal expenses & tips.",
      "Travel insurance.",
      "Dinner & drinks.",
    ],
    additionalInfo: [
      "Free cancellation – up to 24 hours before departure.",
      "Light walking tour, comfortable shoes recommended.",
    ],
    faqs: [
      { q: "How long is the tour?", a: "The tour runs from 9:00 AM to around 5:00 PM." },
      {
        q: "Is this suitable for families?",
        a: "Yes, the tour is family friendly and suitable for all ages.",
      },
    ],
  },
  "newlands-safari-forest": {
    slug: "newlands-safari-forest",
    rating: 4.2,
    reviews: 33,
    destinations: ["Newlands Forest, Cape Town"],
    description:
      "Escape the city into the lush Newlands Forest for a day of gentle hiking, waterfall discovery and wildlife spotting in the shadow of Table Mountain.",
    tourType: "Adventure Tour",
    groupSize: "04-12",
    info: [
      { label: "Accommodation", value: "Not Included" },
      { label: "Meals", value: "Picnic Lunch" },
      { label: "Transportation", value: "Shuttle, Hiking" },
      { label: "Group Size", value: "04-12" },
      { label: "Language", value: "English" },
      { label: "Age Range", value: "10-60 (Year)" },
      { label: "Season", value: "September - May" },
      { label: "Category", value: "Nature, Hiking" },
    ],
    locations: [
      {
        img: `${IMG}/innerpages/package-dt-location-img1.jpg`,
        title: "Newlands Forest",
        days: "01 Day",
      },
    ],
    highlights: [
      "Guided forest hike with Table Mountain views.",
      "Discover hidden waterfalls and pools.",
      "Spot endemic birds and butterflies.",
      "Picnic lunch in a forest clearing.",
      "Braai (BBQ) option at a scenic viewpoint.",
    ],
    itinerary: [
      {
        day: "Day-01",
        title: "Newlands Forest Hike",
        desc: "Meet at the Newlands Forest entrance, hike through indigenous Afromontane forest to the waterfall, enjoy a picnic lunch and descend with panoramic views over Cape Town.",
        transport: "Shuttle, Hiking",
        activities: "Forest hike, Waterfall, Picnic",
        meals: "Picnic Lunch",
        accommodation: "Not Included",
      },
    ],
    includes: [
      "Professional hiking guide.",
      "Shuttle from central Cape Town.",
      "Picnic lunch & water.",
      "National park conservation fee.",
    ],
    excludes: [
      "Hotel accommodation.",
      "Personal expenses & tips.",
      "Travel insurance.",
      "Braai (BBQ) add-on cost.",
    ],
    additionalInfo: [
      "Free cancellation – up to 24 hours before departure.",
      "Moderate fitness level required.",
    ],
    faqs: [
      {
        q: "How challenging is the hike?",
        a: "The main trail is moderate and takes about 4-5 hours including breaks.",
      },
    ],
  },
  "ho-chi-minh-city": {
    slug: "ho-chi-minh-city",
    rating: 4.3,
    reviews: 47,
    destinations: ["Ho Chi Minh City"],
    description:
      "Dive into the energy of Saigon on this one-day tour through historic landmarks, bustling markets and the maze of tunnels that shaped Vietnam's history.",
    tourType: "City Tour",
    groupSize: "05-20",
    info: [
      { label: "Accommodation", value: "Not Included" },
      { label: "Meals", value: "Lunch" },
      { label: "Transportation", value: "Van, Walking" },
      { label: "Group Size", value: "05-20" },
      { label: "Language", value: "English" },
      { label: "Age Range", value: "All Ages" },
      { label: "Season", value: "All Season" },
      { label: "Category", value: "History, City" },
    ],
    locations: [
      {
        img: `${IMG}/innerpages/package-dt-location-img1.jpg`,
        title: "Ben Thanh Market",
        days: "01 Day",
      },
      {
        img: `${IMG}/innerpages/package-dt-location-img2.jpg`,
        title: "Cu Chi Tunnels",
        days: "01 Day",
      },
    ],
    highlights: [
      "Visit the historic Reunification Palace.",
      "See the War Remnants Museum & Notre-Dame Cathedral.",
      "Crawl through the Cu Chi Tunnels.",
      "Sample street food at Ben Thanh Market.",
      "Sunset rooftop drinks overlooking the skyline.",
    ],
    itinerary: [
      {
        day: "Day-01",
        title: "Saigon & Cu Chi Tunnels",
        desc: "Morning city tour of the Reunification Palace, cathedral and Ben Thanh Market, then a half-day trip to the Cu Chi Tunnels for a fascinating underground history lesson.",
        transport: "Van, Walking",
        activities: "City tour, Cu Chi Tunnels",
        meals: "Lunch",
        accommodation: "Not Included",
      },
    ],
    includes: [
      "English-speaking guide.",
      "Van transportation & hotel pickup.",
      "Cu Chi Tunnels entry fee.",
      "Vietnamese lunch.",
      "Bottled water.",
    ],
    excludes: [
      "Hotel accommodation.",
      "Personal expenses & tips.",
      "Travel insurance.",
      "Dinner & drinks.",
    ],
    additionalInfo: [
      "Free cancellation – up to 24 hours before departure.",
      "Comfortable clothing and shoes recommended.",
    ],
    faqs: [
      {
        q: "Do we get to enter the tunnels?",
        a: "Yes, you can crawl through a 100m section of the tunnel system if you wish.",
      },
    ],
  },
  "halong-bay-cruise": {
    slug: "halong-bay-cruise",
    rating: 4.6,
    reviews: 88,
    destinations: ["Halong Bay"],
    description:
      "Sail through the emerald waters and limestone karsts of UNESCO-listed Halong Bay on this unforgettable day cruise with kayaking, caves and a fresh seafood lunch.",
    tourType: "Day Cruise",
    groupSize: "06-30",
    info: [
      { label: "Accommodation", value: "Not Included" },
      { label: "Meals", value: "Seafood Lunch" },
      { label: "Transportation", value: "Bus, Cruise Boat" },
      { label: "Group Size", value: "06-30" },
      { label: "Language", value: "English" },
      { label: "Age Range", value: "All Ages" },
      { label: "Season", value: "All Season" },
      { label: "Category", value: "Cruise, Nature" },
    ],
    locations: [
      {
        img: `${IMG}/innerpages/package-dt-location-img1.jpg`,
        title: "Halong Bay",
        days: "01 Day",
      },
      {
        img: `${IMG}/innerpages/package-dt-location-img2.jpg`,
        title: "Sung Sot Cave",
        days: "01 Day",
      },
    ],
    highlights: [
      "5-hour cruise through Halong Bay's karst islands.",
      "Explore the vast Sung Sot (Surprise) Cave.",
      "Kayak through hidden lagoons.",
      "Fresh seafood lunch served on deck.",
      "Sunset tea & fruit on the sundeck.",
    ],
    itinerary: [
      {
        day: "Day-01",
        title: "Halong Bay Day Cruise",
        desc: "Depart Hanoi early, board a wooden junk boat, cruise past Dau Go island, explore Sung Sot Cave, kayak in a secluded lagoon and enjoy a seafood lunch before returning.",
        transport: "Bus, Cruise Boat, Kayak",
        activities: "Cave visit, Kayaking, Cruise",
        meals: "Seafood Lunch",
        accommodation: "Not Included",
      },
    ],
    includes: [
      "Round-trip hotel transfer from Hanoi.",
      "Day cruise with English-speaking crew.",
      "Sung Sot Cave entry fee.",
      "Kayaking equipment.",
      "Fresh seafood lunch & tea break.",
    ],
    excludes: [
      "Hotel accommodation.",
      "Personal expenses & tips.",
      "Travel insurance.",
      "Dinner & drinks.",
    ],
    additionalInfo: [
      "Free cancellation – up to 24 hours before departure.",
      "Boats have life jackets and safety equipment.",
    ],
    faqs: [
      {
        q: "How long is the cruise?",
        a: "The cruise lasts about 5 hours on the water plus transfer time from Hanoi.",
      },
    ],
  },
  "japan-cherry-blossom": {
    slug: "japan-cherry-blossom",
    rating: 4.7,
    reviews: 143,
    destinations: ["Tokyo", "Kyoto", "Osaka"],
    description:
      "Witness Japan in full bloom on this cherry blossom season tour. From Tokyo's neon streets to Kyoto's tranquil temples, experience the magic of sakura season.",
    tourType: "Group Tour",
    groupSize: "10-18",
    info: [
      { label: "Accommodation", value: "3-4 Star Hotel" },
      { label: "Meals", value: "Breakfast & Dinner" },
      { label: "Transportation", value: "Bullet Train, Bus" },
      { label: "Group Size", value: "10-18" },
      { label: "Language", value: "English" },
      { label: "Age Range", value: "10-65 (Year)" },
      { label: "Season", value: "March - April" },
      { label: "Category", value: "Culture, Spring" },
    ],
    locations: [
      { img: `${IMG}/innerpages/package-dt-location-img1.jpg`, title: "Tokyo", days: "02 Days" },
      { img: `${IMG}/innerpages/package-dt-location-img2.jpg`, title: "Kyoto", days: "03 Days" },
      { img: `${IMG}/innerpages/package-dt-location-img3.jpg`, title: "Osaka", days: "01 Days" },
    ],
    highlights: [
      "Sakura viewing at Ueno Park and Meguro River.",
      "Visit the golden Kinkaku-ji temple in Kyoto.",
      "Fushimi Inari's thousand red torii gates.",
      "Ride the Shinkansen bullet train.",
      "Nara's friendly deer and Great Buddha.",
    ],
    itinerary: [
      {
        day: "Day-01",
        title: "Arrival in Tokyo",
        desc: "Arrive at Narita Airport and transfer to your hotel. Evening welcome dinner with a first glimpse of Tokyo's skyline.",
        transport: "Airport Limousine Bus",
        activities: "Arrival transfer, Welcome dinner",
        meals: "Dinner",
        accommodation: "Tokyo Hotel",
      },
      {
        day: "Day-02",
        title: "Sakura Day in Tokyo",
        desc: "Cherry blossom picnic at Ueno Park, boat ride on the Meguro River under the blossoms and a visit to the Meiji Shrine.",
        transport: "Metro, Walking",
        activities: "Ueno Park, Meguro River, Meiji Shrine",
        meals: "Breakfast, Lunch",
        accommodation: "Tokyo Hotel",
      },
      {
        day: "Day-03",
        title: "Shinkansen to Kyoto",
        desc: "Bullet train through Mt. Fuji country to Kyoto. Afternoon at Kiyomizu-dera temple with views over the city.",
        transport: "Shinkansen",
        activities: "Bullet train, Kiyomizu-dera",
        meals: "Breakfast, Lunch",
        accommodation: "Kyoto Hotel",
      },
      {
        day: "Day-04",
        title: "Golden Pavilion & Arashiyama",
        desc: "Visit Kinkaku-ji, the Golden Pavilion, then stroll the bamboo groves of Arashiyama and the Togetsukyo Bridge.",
        transport: "Bus, Walking",
        activities: "Kinkaku-ji, Bamboo grove",
        meals: "Breakfast, Lunch",
        accommodation: "Kyoto Hotel",
      },
      {
        day: "Day-05",
        title: "Fushimi Inari & Nara Day Trip",
        desc: "Hike the torii-gate tunnel of Fushimi Inari, then take the train to Nara to meet the friendly deer at Todai-ji.",
        transport: "Train, Walking",
        activities: "Fushimi Inari, Nara deer park",
        meals: "Breakfast, Lunch",
        accommodation: "Kyoto Hotel",
      },
      {
        day: "Day-06",
        title: "Osaka & Dotonbori",
        desc: "Day trip to Osaka — Osaka Castle, the bustling Dotonbori food street and an optional takoyaki cooking class.",
        transport: "Train",
        activities: "Osaka Castle, Dotonbori",
        meals: "Breakfast, Dinner",
        accommodation: "Kyoto Hotel",
      },
    ],
    includes: [
      "3-4 star hotel accommodation.",
      "Daily breakfast & selected dinners.",
      "Shinkansen ticket Tokyo – Kyoto.",
      "All entry tickets & temple fees.",
      "English-speaking guide.",
      "JR Pass recommended add-on available.",
    ],
    excludes: [
      "International flights.",
      "Visa fees & processing.",
      "Personal expenses (shopping, tips).",
      "Travel insurance.",
      "Meals not listed in itinerary.",
    ],
    additionalInfo: [
      "Free cancellation – up to 10 days before departure.",
      "Sakura season is weather dependent (late March - mid April).",
      "Temple visits require removing shoes.",
    ],
    faqs: [
      {
        q: "What if the blossoms haven't bloomed?",
        a: "We monitor bloom forecasts and adjust viewing locations to maximize your chances.",
      },
      {
        q: "Is the JR Pass worth it?",
        a: "For this itinerary, a regional rail pass is optional but often saves money on side trips.",
      },
    ],
  },
  "abu-dhabi-luxury-escape": {
    slug: "abu-dhabi-luxury-escape",
    rating: 4.5,
    reviews: 89,
    destinations: ["Abu Dhabi", "Dubai"],
    description:
      "Indulge in the ultimate luxury escape across the Emirates. Sheikh Zayed Grand Mosque, desert safaris, Ferrari World and skyscraper views — all with five-star comfort.",
    tourType: "Private Tour",
    groupSize: "02-08",
    info: [
      { label: "Accommodation", value: "5 Star Hotel" },
      { label: "Meals", value: "Breakfast & Dinner" },
      { label: "Transportation", value: "Private Limo, 4x4" },
      { label: "Group Size", value: "02-08" },
      { label: "Language", value: "English, Arabic" },
      { label: "Age Range", value: "12-70 (Year)" },
      { label: "Season", value: "October - April" },
      { label: "Category", value: "Luxury, Family" },
    ],
    locations: [
      {
        img: `${IMG}/innerpages/package-dt-location-img1.jpg`,
        title: "Abu Dhabi",
        days: "03 Days",
      },
      { img: `${IMG}/innerpages/package-dt-location-img2.jpg`, title: "Dubai", days: "02 Days" },
    ],
    highlights: [
      "Guided tour of the Sheikh Zayed Grand Mosque.",
      "Evening desert safari with dune bashing & BBQ.",
      "Burj Khalifa 'At the Top' observation deck.",
      "Ferrari World & Yas Island theme park day.",
      "Luxury yacht cruise around Abu Dhabi's Corniche.",
    ],
    itinerary: [
      {
        day: "Day-01",
        title: "Arrival in Abu Dhabi",
        desc: "Arrive and transfer to your five-star hotel on the Corniche. Evening welcome dinner with skyline views.",
        transport: "Private Limo",
        activities: "Arrival transfer, Welcome dinner",
        meals: "Dinner",
        accommodation: "Abu Dhabi Hotel",
      },
      {
        day: "Day-02",
        title: "Grand Mosque & Heritage Village",
        desc: "Morning at the Sheikh Zayed Grand Mosque, then Abu Dhabi's Heritage Village and the scenic Corniche waterfront.",
        transport: "Private Limo",
        activities: "Grand Mosque, Heritage Village",
        meals: "Breakfast, Lunch",
        accommodation: "Abu Dhabi Hotel",
      },
      {
        day: "Day-03",
        title: "Desert Safari & BBQ Night",
        desc: "Afternoon dune bashing in a 4x4, camel rides, sandboarding and a starlit BBQ dinner at a desert camp with live entertainment.",
        transport: "4x4",
        activities: "Dune bashing, Camel ride, BBQ",
        meals: "Breakfast, Dinner",
        accommodation: "Abu Dhabi Hotel",
      },
      {
        day: "Day-04",
        title: "Ferrari World & Yas Island",
        desc: "Full day at Yas Island — Ferrari World, the world's fastest roller coaster, and the Yas Marina Circuit.",
        transport: "Private Limo",
        activities: "Ferrari World, Yas Marina",
        meals: "Breakfast",
        accommodation: "Dubai Hotel",
      },
      {
        day: "Day-05",
        title: "Burj Khalifa & Marina Cruise",
        desc: "Transfer to Dubai, visit the Burj Khalifa's observation deck, and end with a dinner cruise around Dubai Marina.",
        transport: "Private Limo, Cruise",
        activities: "Burj Khalifa, Marina cruise",
        meals: "Breakfast, Dinner",
        accommodation: "Dubai Hotel",
      },
    ],
    includes: [
      "5 star hotel accommodation.",
      "Daily breakfast & selected dinners.",
      "Private chauffeured transfers.",
      "Desert safari with BBQ dinner.",
      "Burj Khalifa & Ferrari World tickets.",
      "Marina dinner cruise.",
    ],
    excludes: [
      "International flights.",
      "Visa fees & processing.",
      "Personal expenses (shopping, tips).",
      "Travel insurance.",
      "Meals not listed in itinerary.",
    ],
    additionalInfo: [
      "Free cancellation – up to 72 hours before departure.",
      "Modest dress required at the Grand Mosque.",
      "October to April offers pleasant temperatures.",
    ],
    faqs: [
      {
        q: "Is the desert safari suitable for children?",
        a: "Yes, we offer a family-friendly camp with activities for all ages.",
      },
      {
        q: "Can we add a trip to the Louvre Abu Dhabi?",
        a: "Yes, the Louvre Abu Dhabi can be added to your itinerary.",
      },
    ],
  },
  "morocco-desert-city-adventure": {
    slug: "morocco-desert-city-adventure",
    rating: 4.4,
    reviews: 57,
    destinations: ["Marrakech", "Sahara Desert", "Fes"],
    description:
      "From the souks of Marrakech to the golden dunes of the Sahara, this Moroccan adventure blends imperial cities, desert camps and Berber hospitality.",
    tourType: "Group Tour",
    groupSize: "10-16",
    info: [
      { label: "Accommodation", value: "Riad & Desert Camp" },
      { label: "Meals", value: "Breakfast & Dinner" },
      { label: "Transportation", value: "4x4, Camel" },
      { label: "Group Size", value: "10-16" },
      { label: "Language", value: "English, French" },
      { label: "Age Range", value: "12-65 (Year)" },
      { label: "Season", value: "September - May" },
      { label: "Category", value: "Adventure, Culture" },
    ],
    locations: [
      {
        img: `${IMG}/innerpages/package-dt-location-img1.jpg`,
        title: "Marrakech",
        days: "02 Days",
      },
      {
        img: `${IMG}/innerpages/package-dt-location-img2.jpg`,
        title: "Sahara Desert",
        days: "02 Days",
      },
      { img: `${IMG}/innerpages/package-dt-location-img3.jpg`, title: "Fes", days: "03 Days" },
    ],
    highlights: [
      "Guided tour of Marrakech's medina and souks.",
      "Camel trek into the Erg Chebbi dunes.",
      "Night in a luxury desert camp under the stars.",
      "Cross the dramatic Atlas Mountains.",
      "Explore the ancient tanneries of Fes.",
    ],
    itinerary: [
      {
        day: "Day-01",
        title: "Arrival in Marrakech",
        desc: "Arrive in Marrakech and settle into a traditional riad. Evening exploration of Jemaa el-Fnaa square with its storytellers and food stalls.",
        transport: "Private Van",
        activities: "Arrival, Jemaa el-Fnaa",
        meals: "Dinner",
        accommodation: "Marrakech Riad",
      },
      {
        day: "Day-02",
        title: "Marrakech Souks & Gardens",
        desc: "Morning guided walk through the labyrinthine souks, then the Majorelle Garden, Koutoubia Mosque and Bahia Palace.",
        transport: "Walking",
        activities: "Souks, Majorelle Garden, Palace",
        meals: "Breakfast, Lunch",
        accommodation: "Marrakech Riad",
      },
      {
        day: "Day-03",
        title: "Atlas Mountains to Dades Valley",
        desc: "Cross the High Atlas via the Tizi n'Tichka pass, passing Kasbah Ait Ben Haddou and the dramatic Dades Gorge.",
        transport: "4x4",
        activities: "Mountain drive, Ait Ben Haddou",
        meals: "Breakfast, Dinner",
        accommodation: "Dades Hotel",
      },
      {
        day: "Day-04",
        title: "Camel Trek & Sahara Camp",
        desc: "Arrive at Merzouga, ride camels into the Erg Chebbi dunes and watch the sunset before a campfire night at a luxury desert camp.",
        transport: "4x4, Camel",
        activities: "Camel trek, Desert camp",
        meals: "Breakfast, Dinner",
        accommodation: "Desert Camp",
      },
      {
        day: "Day-05",
        title: "Sunrise Dunes & Fes Road",
        desc: "Watch sunrise over the dunes, then drive north through the Middle Atlas cedar forests to Fes.",
        transport: "4x4",
        activities: "Sunrise, Scenic drive",
        meals: "Breakfast, Dinner",
        accommodation: "Fes Riad",
      },
      {
        day: "Day-06",
        title: "Fes Medina & Tannery",
        desc: "Full day exploring the world's largest car-free medina — the Bou Inania Madrasa, Chouara Tannery and pottery quarter.",
        transport: "Walking",
        activities: "Medina tour, Tannery",
        meals: "Breakfast, Lunch",
        accommodation: "Fes Riad",
      },
      {
        day: "Day-07",
        title: "Departure",
        desc: "Transfer to Fes–Saïss Airport for your departure, or continue to Casablanca on request.",
        transport: "Private Van",
        activities: "Departure transfer",
        meals: "Breakfast",
        accommodation: "–",
      },
    ],
    includes: [
      "Riads & desert camp accommodation.",
      "Daily breakfast & most dinners.",
      "4x4 transport with professional driver.",
      "Camel trek & desert camp night.",
      "Guided medina tours in Marrakech & Fes.",
      "Entry tickets to monuments.",
    ],
    excludes: [
      "International flights.",
      "Visa fees & processing.",
      "Personal expenses (shopping, tips).",
      "Travel insurance.",
      "Lunches & drinks.",
    ],
    additionalInfo: [
      "Free cancellation – up to 5 days before departure.",
      "September to May offers the best desert climate.",
      "Light, modest clothing recommended in medinas.",
    ],
    faqs: [
      {
        q: "Is the desert camp cold at night?",
        a: "Desert nights can be cool; each camp tent includes warm bedding and blankets.",
      },
      {
        q: "Can I ride the camel alone?",
        a: "Yes, camels are guided in a line and no experience is required.",
      },
    ],
  },
  "santorini-island-hopping": {
    slug: "santorini-island-hopping",
    rating: 4.8,
    reviews: 122,
    destinations: ["Santorini", "Mykonos"],
    description:
      "Island hop through the Aegean on this romantic Greek escape. Whitewashed villages, caldera sunsets and beach clubs await in Santorini and Mykonos.",
    tourType: "Honeymoon Tour",
    groupSize: "02-10",
    info: [
      { label: "Accommodation", value: "Cave Suite & Resort" },
      { label: "Meals", value: "Breakfast" },
      { label: "Transportation", value: "Ferry, Car" },
      { label: "Group Size", value: "02-10" },
      { label: "Language", value: "English, Greek" },
      { label: "Age Range", value: "18-65 (Year)" },
      { label: "Season", value: "May - October" },
      { label: "Category", value: "Honeymoon, Beach" },
    ],
    locations: [
      {
        img: `${IMG}/innerpages/package-dt-location-img1.jpg`,
        title: "Santorini",
        days: "02 Days",
      },
      { img: `${IMG}/innerpages/package-dt-location-img2.jpg`, title: "Mykonos", days: "02 Days" },
    ],
    highlights: [
      "Sunset views from the caldera in Oia.",
      "Stay in a traditional cave suite.",
      "Catamaran cruise around Santorini's volcano.",
      "Beach time at Mykonos' Paradise Beach.",
      "Guided winery tour with Greek tasting.",
    ],
    itinerary: [
      {
        day: "Day-01",
        title: "Arrival in Santorini",
        desc: "Arrive at Santorini airport and transfer to your cave suite in Oia. Evening walk to the famous sunset viewpoint.",
        transport: "Private Car",
        activities: "Arrival, Oia sunset",
        meals: "Breakfast",
        accommodation: "Oia Cave Suite",
      },
      {
        day: "Day-02",
        title: "Volcano Catamaran Cruise",
        desc: "Half-day catamaran cruise to the volcanic islets, hot springs swimming and a BBQ lunch on board.",
        transport: "Catamaran",
        activities: "Volcano cruise, Hot springs",
        meals: "Breakfast, Lunch",
        accommodation: "Oia Cave Suite",
      },
      {
        day: "Day-03",
        title: "Winery Tour & Ferry to Mykonos",
        desc: "Morning wine tasting at a caldera-cliff winery, then take the ferry to Mykonos and settle into your resort.",
        transport: "Ferry, Car",
        activities: "Wine tasting, Ferry crossing",
        meals: "Breakfast",
        accommodation: "Mykonos Resort",
      },
      {
        day: "Day-04",
        title: "Beaches & Mykonos Town",
        desc: "Relax at Paradise Beach, then explore the windmills and boutique lanes of Mykonos Town in the evening.",
        transport: "ATV, Walking",
        activities: "Beach day, Mykonos Town",
        meals: "Breakfast",
        accommodation: "Mykonos Resort",
      },
    ],
    includes: [
      "Cave suite & resort accommodation.",
      "Daily breakfast.",
      "Return ferry Santorini – Mykonos.",
      "Catamaran volcano cruise with BBQ.",
      "Winery tour & tasting.",
      "Private airport transfers.",
    ],
    excludes: [
      "International flights.",
      "Visa fees & processing.",
      "Personal expenses (shopping, tips).",
      "Travel insurance.",
      "Lunches & dinners.",
    ],
    additionalInfo: [
      "Free cancellation – up to 72 hours before departure.",
      "May to October offers the best island weather.",
      "Comfortable shoes for caldera stairs.",
    ],
    faqs: [
      {
        q: "How long is the ferry between islands?",
        a: "The high-speed ferry takes about 2 hours between Santorini and Mykonos.",
      },
      {
        q: "Is the catamaran cruise suitable for non-swimmers?",
        a: "Yes, life jackets are provided and swimming is optional.",
      },
    ],
  },
  "santorini-tour": {
    slug: "santorini-tour",
    rating: 4.6,
    reviews: 74,
    destinations: ["Santorini", "Athens"],
    description:
      "A relaxed 8-day exploration of Greece's most photogenic island, with optional day trips to the Acropolis in Athens and the surrounding Cycladic isles.",
    tourType: "Group Tour",
    groupSize: "08-16",
    info: [
      { label: "Accommodation", value: "4 Star Hotel" },
      { label: "Meals", value: "Breakfast" },
      { label: "Transportation", value: "Ferry, Bus" },
      { label: "Group Size", value: "08-16" },
      { label: "Language", value: "English" },
      { label: "Age Range", value: "12-70 (Year)" },
      { label: "Season", value: "May - October" },
      { label: "Category", value: "Island, Culture" },
    ],
    locations: [
      {
        img: `${IMG}/innerpages/package-dt-location-img1.jpg`,
        title: "Santorini",
        days: "06 Days",
      },
      { img: `${IMG}/innerpages/package-dt-location-img2.jpg`, title: "Athens", days: "02 Days" },
    ],
    highlights: [
      "Oia & Fira caldera sunset viewpoints.",
      "Akrotiri archaeological site.",
      "Wine tasting in a volcanic winery.",
      "Red Beach & Kamari black sand beach.",
      "Athens Acropolis & Plaka extension.",
    ],
    itinerary: [
      {
        day: "Day-01",
        title: "Arrival in Santorini",
        desc: "Arrive and transfer to your hotel in Fira. Evening exploration of the caldera edge and Fira town.",
        transport: "Bus",
        activities: "Arrival, Fira walk",
        meals: "Breakfast",
        accommodation: "Fira Hotel",
      },
      {
        day: "Day-02",
        title: "Oia & Sunset",
        desc: "Morning bus to Oia, wander the whitewashed lanes and blue domes, and watch the iconic sunset.",
        transport: "Bus",
        activities: "Oia village, Sunset",
        meals: "Breakfast",
        accommodation: "Fira Hotel",
      },
      {
        day: "Day-03",
        title: "Volcano & Hot Springs",
        desc: "Boat tour to Nea Kameni volcano, swim in the hot springs and visit Palea Kameni.",
        transport: "Boat",
        activities: "Volcano hike, Hot springs",
        meals: "Breakfast",
        accommodation: "Fira Hotel",
      },
      {
        day: "Day-04",
        title: "Akrotiri & Red Beach",
        desc: "Guided visit to the Minoan ruins of Akrotiri, then free time at the dramatic Red Beach.",
        transport: "Bus",
        activities: "Akrotiri, Red Beach",
        meals: "Breakfast",
        accommodation: "Fira Hotel",
      },
      {
        day: "Day-05",
        title: "Winery & Kamari Beach",
        desc: "Morning wine tasting at a volcanic winery, afternoon relaxation at Kamari's black sand beach.",
        transport: "Bus",
        activities: "Wine tasting, Kamari beach",
        meals: "Breakfast",
        accommodation: "Fira Hotel",
      },
      {
        day: "Day-06",
        title: "Ferry to Athens",
        desc: "Morning ferry to Piraeus and transfer to your Athens hotel. Evening stroll through the Plaka neighbourhood.",
        transport: "Ferry, Bus",
        activities: "Ferry crossing, Plaka",
        meals: "Breakfast",
        accommodation: "Athens Hotel",
      },
      {
        day: "Day-07",
        title: "Acropolis & Museum",
        desc: "Guided tour of the Acropolis, Parthenon and the Acropolis Museum, with free afternoon in central Athens.",
        transport: "Walking, Metro",
        activities: "Acropolis, Museum",
        meals: "Breakfast",
        accommodation: "Athens Hotel",
      },
      {
        day: "Day-08",
        title: "Departure",
        desc: "Transfer to Athens International Airport for your departure flight.",
        transport: "Bus",
        activities: "Departure transfer",
        meals: "Breakfast",
        accommodation: "–",
      },
    ],
    includes: [
      "4 star hotel accommodation.",
      "Daily breakfast.",
      "Ferry Santorini – Athens.",
      "Guided tours & entry tickets.",
      "Volcano & hot springs boat trip.",
      "Wine tasting experience.",
    ],
    excludes: [
      "International flights.",
      "Visa fees & processing.",
      "Personal expenses (shopping, tips).",
      "Travel insurance.",
      "Lunches & dinners.",
    ],
    additionalInfo: [
      "Free cancellation – up to 5 days before departure.",
      "May to October offers ideal island weather.",
    ],
    faqs: [
      {
        q: "Is the Acropolis tour included?",
        a: "Yes, the Athens Acropolis guided tour and museum entry are included.",
      },
    ],
  },
  "backwaters-beaches": {
    slug: "backwaters-beaches",
    rating: 4.5,
    reviews: 52,
    destinations: ["Kerala Backwaters", "Kovalam"],
    description:
      "Glide through Kerala's serene backwaters on a traditional houseboat, then unwind on the golden beaches of the Arabian Sea on this tranquil southern India escape.",
    tourType: "Group Tour",
    groupSize: "06-16",
    info: [
      { label: "Accommodation", value: "Houseboat & Resort" },
      { label: "Meals", value: "Full Board (Houseboat)" },
      { label: "Transportation", value: "Car, Houseboat" },
      { label: "Group Size", value: "06-16" },
      { label: "Language", value: "English" },
      { label: "Age Range", value: "10-70 (Year)" },
      { label: "Season", value: "September - March" },
      { label: "Category", value: "Nature, Relaxation" },
    ],
    locations: [
      { img: `${IMG}/innerpages/package-dt-location-img1.jpg`, title: "Alleppey", days: "03 Days" },
      { img: `${IMG}/innerpages/package-dt-location-img2.jpg`, title: "Kovalam", days: "04 Days" },
    ],
    highlights: [
      "Two nights aboard a traditional Kettuvallam houseboat.",
      "Canal cruises through palm-fringed villages.",
      "Kathakali dance performance.",
      "Ayurvedic spa treatments in Kovalam.",
      "Beach time at the famous Kovalam lighthouse.",
    ],
    itinerary: [
      {
        day: "Day-01",
        title: "Arrival & Kochi Sights",
        desc: "Arrive in Kochi, visit Fort Kochi's Chinese fishing nets and the St. Francis Church, then drive to Alleppey.",
        transport: "Private Car",
        activities: "Fort Kochi, Transfer",
        meals: "Dinner",
        accommodation: "Alleppey Hotel",
      },
      {
        day: "Day-02",
        title: "Houseboat Cruise Begins",
        desc: "Board your private houseboat and cruise the backwaters through Punnamada Lake and narrow canals. Full board on board.",
        transport: "Houseboat",
        activities: "Backwater cruise, Canal tour",
        meals: "Breakfast, Lunch, Dinner",
        accommodation: "Houseboat",
      },
      {
        day: "Day-03",
        title: "Village Life & Beach",
        desc: "Morning village walking tour, then drive to Kovalam for sunset at the lighthouse beach.",
        transport: "Houseboat, Car",
        activities: "Village tour, Lighthouse beach",
        meals: "Breakfast, Lunch",
        accommodation: "Kovalam Resort",
      },
      {
        day: "Day-04",
        title: "Kathakali & Ayurveda",
        desc: "Morning ayurvedic massage, then watch a traditional Kathakali dance performance in the evening.",
        transport: "Car",
        activities: "Ayurveda, Kathakali show",
        meals: "Breakfast, Dinner",
        accommodation: "Kovalam Resort",
      },
      {
        day: "Day-05",
        title: "Leisure at Kovalam",
        desc: "Free day — swim, relax or take an optional fishing village tour.",
        transport: "–",
        activities: "Free time, Beach",
        meals: "Breakfast",
        accommodation: "Kovalam Resort",
      },
      {
        day: "Day-06",
        title: "Poovar Backwaters",
        desc: "Boat ride on the Poovar backwaters where the river meets the sea, with a stop at a golden sandbar.",
        transport: "Boat, Car",
        activities: "Poovar cruise, Sandbar",
        meals: "Breakfast, Lunch",
        accommodation: "Kovalam Resort",
      },
      {
        day: "Day-07",
        title: "Departure",
        desc: "Drive to Trivandrum International Airport for your departure flight.",
        transport: "Private Car",
        activities: "Departure transfer",
        meals: "Breakfast",
        accommodation: "–",
      },
    ],
    includes: [
      "Hotel, resort & 2-night houseboat stay.",
      "Full board while on the houseboat.",
      "Daily breakfast elsewhere.",
      "Kathakali performance ticket.",
      "Ayurvedic spa session.",
      "All local transfers.",
    ],
    excludes: [
      "International flights.",
      "Visa fees & processing.",
      "Personal expenses (shopping, tips).",
      "Travel insurance.",
      "Lunches & dinners outside houseboat.",
    ],
    additionalInfo: [
      "Free cancellation – up to 5 days before departure.",
      "Best visited between September and March.",
    ],
    faqs: [
      {
        q: "How many people fit on the houseboat?",
        a: "Each houseboat sleeps 2-6 guests with private cabins and an onboard chef.",
      },
    ],
  },
};

export function getPackageBySlug(slug: string): Pkg | undefined {
  return allPackages.find((p) => p.slug === slug);
}

const TOUR_TYPE_BY_CATEGORY: Record<string, string> = {
  group: "Group Tour",
  honeymoon: "Honeymoon Tour",
  corporate: "Corporate Tour",
  customized: "Customized Tour",
  educational: "Educational Tour",
};

function parseDays(duration?: string): number {
  if (!duration) return 5;
  const m = duration.match(/(\d+)\s*Days?/i);
  const n = m ? Number(m[1]) : 5;
  return Math.min(Math.max(n, 1), 9);
}

function buildPackageDetail(pkg: Pkg): PackageDetail {
  const days = parseDays(pkg.duration);
  const type = TOUR_TYPE_BY_CATEGORY[pkg.category ?? "group"] ?? "Group Tour";
  const dest = pkg.location.split(",").map((s) => s.trim());
  const itinerary: PackageDetail["itinerary"] = Array.from({ length: days }, (_, i) => ({
    day: `Day-0${i + 1}`,
    title:
      i === 0
        ? `Arrival & Welcome to ${dest[0]}`
        : i === days - 1
          ? "Leisure & Departure"
          : `Explore ${dest[0]} Highlights`,
    desc:
      i === 0
        ? `Arrive in ${dest[0]}, complete your transfer and check-in, then enjoy a welcome orientation and first evening at leisure.`
        : i === days - 1
          ? "A relaxed morning before your departure transfer. Optional shopping and souvenir time before your flight home."
          : `A full day of guided sightseeing across the top attractions of ${dest[0]}, with photo stops, local cuisine and free time to explore.`,
    transport: "Private AC Vehicle",
    activities:
      i === 0
        ? "Arrival transfer, Welcome orientation"
        : i === days - 1
          ? "Leisure, Departure transfer"
          : "Guided sightseeing, Photo stops",
    meals: "Breakfast, Dinner",
    accommodation: "4 Star Hotel",
  }));

  return {
    slug: pkg.slug,
    rating: pkg.rating ?? 4.5,
    reviews: pkg.reviews ?? 40,
    destinations: dest,
    description: `${pkg.title} — a hand-crafted ${type.toLowerCase()} package from Travel Nest. Enjoy ${pkg.duration ?? "a memorable journey"} of curated sightseeing, comfortable stays, seamless transfers and 24/7 support so you can focus on making unforgettable memories in ${pkg.location}.`,
    tourType: type,
    groupSize: "02-15",
    info: [
      { label: "Accommodation", value: "4 Star Hotel" },
      { label: "Meals", value: "Daily Breakfast" },
      { label: "Transportation", value: "Private AC Vehicle" },
      { label: "Group Size", value: "02-15" },
      { label: "Language", value: "English" },
      { label: "Age Range", value: "All Ages" },
      { label: "Season", value: "All Season" },
      { label: "Category", value: type },
    ],
    locations: Array.from({ length: Math.min(3, dest.length) }, (_, i) => ({
      img: pkg.images[i % pkg.images.length],
      title: dest[i],
      days: i === 0 ? "01 Days" : "02 Days",
    })),
    highlights: [
      `Curated itinerary covering the best of ${pkg.location}.`,
      "4 star accommodation with daily breakfast.",
      "Comfortable private transfers throughout.",
      "Guided sightseeing at every major highlight.",
      "Visa facilitation and 24/7 Travel Nest support.",
    ],
    itinerary,
    includes: [
      "Return air tickets.",
      "4 star hotel accommodation.",
      "Daily breakfast.",
      "Tours & transfers.",
      "Visa facilitation.",
      "24/7 support.",
    ],
    excludes: [
      "Travel insurance.",
      "Personal expenses (shopping, tips).",
      "Lunches & dinners unless stated.",
      "Optional activities not listed.",
    ],
    additionalInfo: [
      "Free cancellation – up to 5 days before departure.",
      "Group discounts available for 6+ travellers.",
    ],
    faqs: [
      {
        q: `Is the ${pkg.title} package customizable?`,
        a: "Yes — our team can tailor dates, hotels and activities to your preferences.",
      },
      {
        q: "How do I confirm my booking?",
        a: "Contact Travel Nest on WhatsApp or phone and our team will guide you through the process.",
      },
    ],
  };
}

export function getPackageDetail(slug: string): PackageDetail | undefined {
  const detail = packageDetails[slug];
  if (detail) return detail;
  const pkg = getPackageBySlug(slug);
  if (!pkg) return undefined;
  return buildPackageDetail(pkg);
}
