/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AirTicketsRouteImport } from './routes/air-tickets'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporateToursRouteImport } from './routes/corporate-tours'
import { Route as CruisesRouteImport } from './routes/cruises'
import { Route as CustomizedToursRouteImport } from './routes/customized-tours'
import { Route as DestinationWeddingRouteImport } from './routes/destination-wedding'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as EducationalToursRouteImport } from './routes/educational-tours'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GroupToursRouteImport } from './routes/group-tours'
import { Route as HoneymoonTripsRouteImport } from './routes/honeymoon-trips'
import { Route as HotelBookingsRouteImport } from './routes/hotel-bookings'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TransportationRouteImport } from './routes/transportation'
import { Route as VisaFacilitationRouteImport } from './routes/visa-facilitation'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminToursRouteImport } from './routes/admin.tours'
import { Route as AdminVisaRouteImport } from './routes/admin.visa'
import { Route as PackagesIndexRouteImport } from './routes/packages/index'
import { Route as PackagesSlugRouteImport } from './routes/packages.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AirTicketsRoute = AirTicketsRouteImport.update({
  id: '/air-tickets',
  path: '/air-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateToursRoute = CorporateToursRouteImport.update({
  id: '/corporate-tours',
  path: '/corporate-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const CruisesRoute = CruisesRouteImport.update({
  id: '/cruises',
  path: '/cruises',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizedToursRoute = CustomizedToursRouteImport.update({
  id: '/customized-tours',
  path: '/customized-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationWeddingRoute = DestinationWeddingRouteImport.update({
  id: '/destination-wedding',
  path: '/destination-wedding',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationalToursRoute = EducationalToursRouteImport.update({
  id: '/educational-tours',
  path: '/educational-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupToursRoute = GroupToursRouteImport.update({
  id: '/group-tours',
  path: '/group-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const HoneymoonTripsRoute = HoneymoonTripsRouteImport.update({
  id: '/honeymoon-trips',
  path: '/honeymoon-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelBookingsRoute = HotelBookingsRouteImport.update({
  id: '/hotel-bookings',
  path: '/hotel-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportationRoute = TransportationRouteImport.update({
  id: '/transportation',
  path: '/transportation',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaFacilitationRoute = VisaFacilitationRouteImport.update({
  id: '/visa-facilitation',
  path: '/visa-facilitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToursRoute = AdminToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisaRoute = AdminVisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => AdminRoute,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackagesRoute,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PackagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/air-tickets': typeof AirTicketsRoute
  '/contact': typeof ContactRoute
  '/corporate-tours': typeof CorporateToursRoute
  '/cruises': typeof CruisesRoute
  '/customized-tours': typeof CustomizedToursRoute
  '/destination-wedding': typeof DestinationWeddingRoute
  '/destinations': typeof DestinationsRoute
  '/educational-tours': typeof EducationalToursRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/group-tours': typeof GroupToursRoute
  '/honeymoon-trips': typeof HoneymoonTripsRoute
  '/hotel-bookings': typeof HotelBookingsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/transportation': typeof TransportationRoute
  '/visa-facilitation': typeof VisaFacilitationRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/visa': typeof AdminVisaRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/packages/': typeof PackagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/air-tickets': typeof AirTicketsRoute
  '/contact': typeof ContactRoute
  '/corporate-tours': typeof CorporateToursRoute
  '/cruises': typeof CruisesRoute
  '/customized-tours': typeof CustomizedToursRoute
  '/destination-wedding': typeof DestinationWeddingRoute
  '/destinations': typeof DestinationsRoute
  '/educational-tours': typeof EducationalToursRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/group-tours': typeof GroupToursRoute
  '/honeymoon-trips': typeof HoneymoonTripsRoute
  '/hotel-bookings': typeof HotelBookingsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/transportation': typeof TransportationRoute
  '/visa-facilitation': typeof VisaFacilitationRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/visa': typeof AdminVisaRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/packages': typeof PackagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/air-tickets': typeof AirTicketsRoute
  '/contact': typeof ContactRoute
  '/corporate-tours': typeof CorporateToursRoute
  '/cruises': typeof CruisesRoute
  '/customized-tours': typeof CustomizedToursRoute
  '/destination-wedding': typeof DestinationWeddingRoute
  '/destinations': typeof DestinationsRoute
  '/educational-tours': typeof EducationalToursRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/group-tours': typeof GroupToursRoute
  '/honeymoon-trips': typeof HoneymoonTripsRoute
  '/hotel-bookings': typeof HotelBookingsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/transportation': typeof TransportationRoute
  '/visa-facilitation': typeof VisaFacilitationRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/visa': typeof AdminVisaRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/packages/': typeof PackagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/air-tickets'
    | '/contact'
    | '/corporate-tours'
    | '/cruises'
    | '/customized-tours'
    | '/destination-wedding'
    | '/destinations'
    | '/educational-tours'
    | '/experiences'
    | '/gallery'
    | '/group-tours'
    | '/honeymoon-trips'
    | '/hotel-bookings'
    | '/packages'
    | '/privacy'
    | '/terms'
    | '/transportation'
    | '/visa-facilitation'
    | '/admin/banners'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/tours'
    | '/admin/visa'
    | '/packages/$slug'
    | '/packages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/air-tickets'
    | '/contact'
    | '/corporate-tours'
    | '/cruises'
    | '/customized-tours'
    | '/destination-wedding'
    | '/destinations'
    | '/educational-tours'
    | '/experiences'
    | '/gallery'
    | '/group-tours'
    | '/honeymoon-trips'
    | '/hotel-bookings'
    | '/privacy'
    | '/terms'
    | '/transportation'
    | '/visa-facilitation'
    | '/admin/banners'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/tours'
    | '/admin/visa'
    | '/packages/$slug'
    | '/packages'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/air-tickets'
    | '/contact'
    | '/corporate-tours'
    | '/cruises'
    | '/customized-tours'
    | '/destination-wedding'
    | '/destinations'
    | '/educational-tours'
    | '/experiences'
    | '/gallery'
    | '/group-tours'
    | '/honeymoon-trips'
    | '/hotel-bookings'
    | '/packages'
    | '/privacy'
    | '/terms'
    | '/transportation'
    | '/visa-facilitation'
    | '/admin/banners'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/tours'
    | '/admin/visa'
    | '/packages/$slug'
    | '/packages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AirTicketsRoute: typeof AirTicketsRoute
  ContactRoute: typeof ContactRoute
  CorporateToursRoute: typeof CorporateToursRoute
  CruisesRoute: typeof CruisesRoute
  CustomizedToursRoute: typeof CustomizedToursRoute
  DestinationWeddingRoute: typeof DestinationWeddingRoute
  DestinationsRoute: typeof DestinationsRoute
  EducationalToursRoute: typeof EducationalToursRoute
  ExperiencesRoute: typeof ExperiencesRoute
  GalleryRoute: typeof GalleryRoute
  GroupToursRoute: typeof GroupToursRoute
  HoneymoonTripsRoute: typeof HoneymoonTripsRoute
  HotelBookingsRoute: typeof HotelBookingsRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TransportationRoute: typeof TransportationRoute
  VisaFacilitationRoute: typeof VisaFacilitationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/air-tickets': {
      id: '/air-tickets'
      path: '/air-tickets'
      fullPath: '/air-tickets'
      preLoaderRoute: typeof AirTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-tours': {
      id: '/corporate-tours'
      path: '/corporate-tours'
      fullPath: '/corporate-tours'
      preLoaderRoute: typeof CorporateToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruises': {
      id: '/cruises'
      path: '/cruises'
      fullPath: '/cruises'
      preLoaderRoute: typeof CruisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customized-tours': {
      id: '/customized-tours'
      path: '/customized-tours'
      fullPath: '/customized-tours'
      preLoaderRoute: typeof CustomizedToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination-wedding': {
      id: '/destination-wedding'
      path: '/destination-wedding'
      fullPath: '/destination-wedding'
      preLoaderRoute: typeof DestinationWeddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educational-tours': {
      id: '/educational-tours'
      path: '/educational-tours'
      fullPath: '/educational-tours'
      preLoaderRoute: typeof EducationalToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-tours': {
      id: '/group-tours'
      path: '/group-tours'
      fullPath: '/group-tours'
      preLoaderRoute: typeof GroupToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honeymoon-trips': {
      id: '/honeymoon-trips'
      path: '/honeymoon-trips'
      fullPath: '/honeymoon-trips'
      preLoaderRoute: typeof HoneymoonTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-bookings': {
      id: '/hotel-bookings'
      path: '/hotel-bookings'
      fullPath: '/hotel-bookings'
      preLoaderRoute: typeof HotelBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportation': {
      id: '/transportation'
      path: '/transportation'
      fullPath: '/transportation'
      preLoaderRoute: typeof TransportationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa-facilitation': {
      id: '/visa-facilitation'
      path: '/visa-facilitation'
      fullPath: '/visa-facilitation'
      preLoaderRoute: typeof VisaFacilitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tours': {
      id: '/admin/tours'
      path: '/tours'
      fullPath: '/admin/tours'
      preLoaderRoute: typeof AdminToursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visa': {
      id: '/admin/visa'
      path: '/visa'
      fullPath: '/admin/visa'
      preLoaderRoute: typeof AdminVisaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/packages/': {
      id: '/packages/'
      path: '/'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof PackagesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminToursRoute: typeof AdminToursRoute
  AdminVisaRoute: typeof AdminVisaRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminToursRoute: AdminToursRoute,
  AdminVisaRoute: AdminVisaRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PackagesRouteChildren {
  PackagesSlugRoute: typeof PackagesSlugRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesSlugRoute: PackagesSlugRoute,
  PackagesIndexRoute: PackagesIndexRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AirTicketsRoute: AirTicketsRoute,
  ContactRoute: ContactRoute,
  CorporateToursRoute: CorporateToursRoute,
  CruisesRoute: CruisesRoute,
  CustomizedToursRoute: CustomizedToursRoute,
  DestinationWeddingRoute: DestinationWeddingRoute,
  DestinationsRoute: DestinationsRoute,
  EducationalToursRoute: EducationalToursRoute,
  ExperiencesRoute: ExperiencesRoute,
  GalleryRoute: GalleryRoute,
  GroupToursRoute: GroupToursRoute,
  HoneymoonTripsRoute: HoneymoonTripsRoute,
  HotelBookingsRoute: HotelBookingsRoute,
  PackagesRoute: PackagesRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TransportationRoute: TransportationRoute,
  VisaFacilitationRoute: VisaFacilitationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
